<!doctype html><html lang="de"><head><meta charset="utf-8"><style>
@page{margin:22mm 18mm}*{box-sizing:border-box}body{font-family:{{ $template['font'] }};font-size:10.5pt;color:#27272a;line-height:1.45;margin:0}
h1,h2,h3,p{margin:0}header{padding:0 0 15px;border-bottom:3px solid {{ $template['color'] }};margin-bottom:18px}h1{font-size:27pt;color:{{ $template['color'] }}}header .headline{font-size:13pt;margin-top:3px}.goal{margin-top:10px;color:#52525b}
section{margin-top:17px;page-break-inside:auto}h2{font-size:13pt;text-transform:uppercase;letter-spacing:1px;color:{{ $template['color'] }};border-bottom:1px solid #d4d4d8;padding-bottom:3px;margin-bottom:8px}.entry{margin:0 0 12px;page-break-inside:avoid}.row{width:100%}.row td{vertical-align:top}.date{text-align:right;white-space:nowrap;color:#52525b;width:28%}h3{font-size:11pt}.meta,.level{color:#52525b;font-size:9.5pt}.description{white-space:pre-line;margin-top:4px}
@if($template['style']==='sidebar') body{border-left:14mm solid {{ $template['color'] }};padding-left:9mm}@endif
@if($template['style']==='minimal') header{border-bottom-width:1px}h1{color:#18181b}h2{letter-spacing:2px}@endif
@if($template['style']==='executive') h1{text-transform:uppercase;letter-spacing:1.5px}h2{background:{{ $template['color'] }};color:white;padding:4px 7px;border:0}@endif
@if($template['style']==='creative') header{background:{{ $template['color'] }};color:white;padding:15px}header h1{color:white}header .goal{color:white}h2{border-left:5px solid {{ $template['color'] }};padding-left:7px;border-bottom:0}@endif
@if($template['style']==='modern') h2{border:0;background:#f4f4f5;padding:5px 8px}header{text-align:center}@endif
footer{position:fixed;bottom:-13mm;left:0;right:0;text-align:center;color:#a1a1aa;font-size:8pt}
</style></head><body>
@php($labels=['experience'=>'Berufserfahrung','education'=>'Ausbildung & Bildung','qualification'=>'Qualifikationen','language'=>'Sprachen','skill'=>'Kenntnisse'])
<header><h1>{{ $version->snapshot['person']['vorname'] }} {{ $version->snapshot['person']['nachname'] }}</h1><p class="headline">{{ data_get($version->snapshot,'profile.professional_headline') }}</p>@if(data_get($version->snapshot,'profile.career_goal'))<p class="goal">{{ data_get($version->snapshot,'profile.career_goal') }}</p>@endif</header>
@foreach($labels as $type=>$label) @php($entries=collect($version->snapshot['entries'])->where('type',$type)) @if($entries->isNotEmpty())<section><h2>{{ $label }}</h2>@foreach($entries as $entry)<div class="entry"><table class="row"><tr><td><h3>{{ $entry['title'] }}</h3><p class="meta">{{ $entry['organization'] ?? '' }}@if(!empty($entry['organization'])&&!empty($entry['location'])) · @endif{{ $entry['location'] ?? '' }}</p></td><td class="date">{{ !empty($entry['starts_at'])?substr($entry['starts_at'],0,7):'' }}@if(!empty($entry['starts_at'])) – {{ !empty($entry['current'])?'heute':substr($entry['ends_at']??'',0,7) }}@endif</td></tr></table>@if(!empty($entry['proficiency']))<p class="level">Niveau: {{ $entry['proficiency'] }}</p>@endif @if(!empty($entry['description']))<p class="description">{{ $entry['description'] }}</p>@endif</div>@endforeach</section>@endif @endforeach
<footer>Lebenslauf · Version {{ $version->version }} · {{ $template['name'] }}</footer></body></html>
