const defaultTheme = require('tailwindcss/defaultTheme');

/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './vendor/laravel/jetstream/**/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.vue',
    ],
    darkMode: "class",
    theme: {
        extend: {
            fontFamily: {
                //'Helvetica, Figtree'
                Helvetica: ['Helvetica', ...defaultTheme.fontFamily.sans],
                Montserrat: ['Montserrat', 'sans-serif'],
            },
            colors:{
                zbb: '#ff8500',
                zbbTrp: 'rgba(255, 133, 0, 0.1)',
                chip: '#FFF3E0',
                danger: '#ff0000',
                success: '#16a34a',
                warning: '#eab308',
                info: '#3b82f6',
                air: {
                    bg: '#f7fbff',
                    card: '#ffffff',
                    primary: '#102033',
                    secondary: '#5d6b7e',
                    success: '#22c55e',
                    error: '#ef4444',
                    border: '#d7e4ef',
                    borderHover: '#38bdf8',
                    muted: '#eaf4fb',
                    buttonPrimary: '#0ea5e9',
                    inputBg: '#ffffff',
                    table: '#f1f7fb',
                    buttonTextPrimary: '#ffffff',
                    buttonTextSecondary: '#123047',
                    buttonPrimaryHover: '#0284c7',
                    progress: '#0ea5e9',
                },
                dark: {
                    bg: '#0c1016',
                    card: '#121821',
                    primary: '#f4f7fb',
                    secondary: '#aab6c5',
                    success: '#34d399',
                    error: '#fb7185',
                    border: '#263241',
                    borderHover: '#60a5fa',
                    muted: '#1d2633',
                    buttonPrimary: '#f4f7fb',
                    inputBg: '#0f1520',
                    table: '#151b23',
                    buttonTextPrimary: '#0c1016',
                    buttonTextSecondary: '#f4f7fb',
                    buttonPrimaryHover: '#c7d2fe',
                    progress: '#60a5fa',
                },
                womanly: {
                    bg: '#fff7fb',
                    card: '#ffffff',
                    primary: '#43223b',
                    secondary: '#8a5b7d',
                    success: '#16a34a',
                    error: '#e11d48',
                    border: '#f1cfe0',
                    borderHover: '#db2777',
                    muted: '#fde8f2',
                    buttonPrimary: '#be185d',
                    inputBg: '#fffafd',
                    table: '#fff0f7',
                    buttonTextPrimary: '#ffffff',
                    buttonTextSecondary: '#5c294f',
                    buttonPrimaryHover: '#9d174d',
                    progress: '#db2777',
                },
                champion: {
                    bg: '#fffaf0',
                    card: '#ffffff',
                    primary: '#2f2412',
                    secondary: '#7a5a22',
                    success: '#16a34a',
                    error: '#dc2626',
                    border: '#f2d89b',
                    borderHover: '#d97706',
                    muted: '#fff1c2',
                    buttonPrimary: '#b45309',
                    inputBg: '#fffdf7',
                    table: '#fff6d8',
                    buttonTextPrimary: '#ffffff',
                    buttonTextSecondary: '#4a3412',
                    buttonPrimaryHover: '#92400e',
                    progress: '#d97706',
                },
                sprint: {
                    bg: '#f5fff9',
                    card: '#ffffff',
                    primary: '#0b2f24',
                    secondary: '#437063',
                    success: '#059669',
                    error: '#e11d48',
                    border: '#bfe8d8',
                    borderHover: '#10b981',
                    muted: '#dcfce7',
                    buttonPrimary: '#059669',
                    inputBg: '#fbfffd',
                    table: '#ecfdf5',
                    buttonTextPrimary: '#ffffff',
                    buttonTextSecondary: '#0f3f31',
                    buttonPrimaryHover: '#047857',
                    progress: '#10b981',
                },
                arena: {
                    bg: '#f8fafc',
                    card: '#ffffff',
                    primary: '#1e293b',
                    secondary: '#64748b',
                    success: '#16a34a',
                    error: '#dc2626',
                    border: '#cbd5e1',
                    borderHover: '#475569',
                    muted: '#e2e8f0',
                    buttonPrimary: '#334155',
                    inputBg: '#ffffff',
                    table: '#f1f5f9',
                    buttonTextPrimary: '#ffffff',
                    buttonTextSecondary: '#334155',
                    buttonPrimaryHover: '#1e293b',
                    progress: '#64748b',
                },
                pulse: {
                    bg: '#fff7ed',
                    card: '#ffffff',
                    primary: '#3b1d0f',
                    secondary: '#8a4b2a',
                    success: '#16a34a',
                    error: '#dc2626',
                    border: '#fed7aa',
                    borderHover: '#f97316',
                    muted: '#ffedd5',
                    buttonPrimary: '#ea580c',
                    inputBg: '#fffaf5',
                    table: '#fff3e0',
                    buttonTextPrimary: '#ffffff',
                    buttonTextSecondary: '#5f2f17',
                    buttonPrimaryHover: '#c2410c',
                    progress: '#f97316',
                },
                trail: {
                    bg: '#f6f8f2',
                    card: '#ffffff',
                    primary: '#24301b',
                    secondary: '#657252',
                    success: '#15803d',
                    error: '#dc2626',
                    border: '#d6dfc6',
                    borderHover: '#65a30d',
                    muted: '#edf5df',
                    buttonPrimary: '#4d7c0f',
                    inputBg: '#fbfdf7',
                    table: '#eef6e2',
                    buttonTextPrimary: '#ffffff',
                    buttonTextSecondary: '#31411f',
                    buttonPrimaryHover: '#3f6212',
                    progress: '#65a30d',
                },
                bazaar: {
                    bg: '#e7f8fb',
                    card: '#ffffff',
                    primary: '#172033',
                    secondary: '#667085',
                    success: '#16a34a',
                    error: '#dc2626',
                    border: '#b8e3ea',
                    borderHover: '#ff8a00',
                    muted: '#fff3df',
                    buttonPrimary: '#ff8a00',
                    inputBg: '#ffffff',
                    table: '#f4fbfc',
                    buttonTextPrimary: '#ffffff',
                    buttonTextSecondary: '#172033',
                    buttonPrimaryHover: '#e67600',
                    progress: '#00a8c6',
                },
                vital: {
                    bg: '#FFFFFF',
                    card: '#FFFFFF',
                    primary: '#262827',
                    secondary: '#5D625F',
                    success: '#6CC63A',
                    error: '#dc2626',
                    border: '#D7DED7',
                    borderHover: '#6CC63A',
                    muted: '#EDEDED',
                    buttonPrimary: '#6CC63A',
                    inputBg: '#FFFFFF',
                    table: '#F6F8F5',
                    buttonTextPrimary: '#151515',
                    buttonTextSecondary: '#262827',
                    buttonPrimaryHover: '#58A932',
                    progress: '#8ED34A',
                },
                bg: 'var(--bg)',
                card: 'var(--card)',
                primary: 'var(--primary)',
                secondary: 'var(--secondary)',
                border: 'var(--border)',
                borderHover: 'var(--borderHover)',
                muted: 'var(--muted)',
                buttonPrimary: 'var(--buttonPrimary)',
                inputBg: 'var(--inputBg)',
                table: 'var(--table)',
                buttonTextPrimary: 'var(--buttonTextPrimary)',
                buttonTextSecondary: 'var(--buttonTextSecondary)',
                buttonPrimaryHover: 'var(--buttonPrimaryHover)',
                progress: 'var(--progress)',
            },

        },
    },

    plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography')],
};
