<script setup>
import { computed } from 'vue'; import { Head, Link, router } from '@inertiajs/vue3'; import ParticipantPortalLayout from '@/Layouts/ParticipantPortalLayout.vue';
const props=defineProps({participant:Object,participations:{type:Array,default:()=>[]},profile:Object,reminders:{type:Array,default:()=>[]},unreadMessageCount:{type:Number,default:0}});
const openTasks=computed(()=>(props.participations||[]).flatMap((item)=>item.tasks||[]));
const enabled=(key)=>props.participations.some((item)=>item.portal_features?.[key]);
const cards=computed(()=>[
 {title:'Jobs & Bewerbungen',text:'Stellen finden, merken und Bewerbungen verfolgen.',route:'participant-portal.jobs.index',tone:'from-cyan-500 to-blue-600',icon:'↗',show:enabled('job_search')||enabled('application_management')},
 {title:'Kurse & Lernen',text:'Lektionen, Aufgaben, Quiz und Lernfortschritt.',route:'participant-portal.learning.index',tone:'from-violet-500 to-indigo-600',icon:'◇',show:enabled('learning')},
 {title:'Anwesenheit & Aufgaben',text:'Eigene Zeiten, Saldo, Termine und Korrekturanfragen.',route:'participant-portal.self-service.index',tone:'from-emerald-500 to-teal-600',icon:'✓',show:enabled('attendance_self_service')||enabled('tasks_and_appointments')},
 {title:'Dokumente',text:'Unterlagen sicher hochladen und verwalten.',route:'participant-portal.documents.index',tone:'from-orange-400 to-rose-500',icon:'▤',show:enabled('profile')},
 {title:'Lebenslauf',text:'Berufliches Profil strukturiert vervollständigen.',route:'participant-portal.resume.index',tone:'from-slate-600 to-slate-800',icon:'◎',show:enabled('profile')},
 {title:'Nachrichten',text:'Direkter Austausch mit Ihrem Projektteam.',route:'participant-portal.messages.index',tone:'from-fuchsia-500 to-purple-600',icon:'✉',show:enabled('messaging')},
].filter((item)=>item.show));
const profileFields=['professional_headline','career_goal','skills','interests'];const profileCompleted=computed(()=>profileFields.filter((key)=>props.profile?.[key]?.trim()).length);const profilePercent=computed(()=>Math.round(profileCompleted.value/profileFields.length*100));
const typeLabel={message:'Nachricht',application:'Bewerbung',course_session:'Kurstermin',course:'Kurs',task:'Aufgabe'};
const logout=()=>router.post(route('participant-portal.logout'));
</script>
<template><Head title="Mein Portal"/><ParticipantPortalLayout :title="`Hallo ${participant.vorname || ''}`" subtitle="Hier finden Sie Ihre nächsten Schritte, Projekte und persönlichen Unterlagen.">
 <template #actions><Link :href="route('participant-portal.notification-preferences.index')" class="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 shadow-sm hover:border-slate-300">Hinweise einstellen</Link><button type="button" class="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-slate-800" @click="logout">Abmelden</button></template>
 <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="rounded-2xl border border-white/80 bg-white/90 p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wider text-slate-500">Meine Projekte</p><p class="mt-2 text-3xl font-bold">{{ participations.length }}</p><p class="mt-1 text-sm text-slate-500">aktive Zuordnungen</p></div><div class="rounded-2xl border border-white/80 bg-white/90 p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wider text-slate-500">Offene Aufgaben</p><p class="mt-2 text-3xl font-bold">{{ openTasks.length }}</p><p class="mt-1 text-sm text-slate-500">für Sie sichtbar</p></div><div class="rounded-2xl border border-white/80 bg-white/90 p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wider text-slate-500">Ungelesen</p><p class="mt-2 text-3xl font-bold">{{ unreadMessageCount }}</p><p class="mt-1 text-sm text-slate-500">Nachrichten</p></div><div class="rounded-2xl bg-slate-950 p-5 text-white shadow-lg"><div class="flex justify-between"><p class="text-xs font-bold uppercase tracking-wider text-cyan-300">Profil</p><span class="text-sm font-semibold">{{ profilePercent }} %</span></div><div class="mt-4 h-2 overflow-hidden rounded-full bg-white/15"><div class="h-full rounded-full bg-gradient-to-r from-cyan-300 to-orange-300" :style="{width:`${profilePercent}%`}"></div></div><Link v-if="enabled('profile')" :href="route('participant-portal.resume.index')" class="mt-3 inline-block text-sm font-semibold text-white">Jetzt vervollständigen →</Link></div></section>
 <div class="mt-7 grid gap-6 xl:grid-cols-[1fr_380px]"><div class="space-y-7"><section><div class="mb-4 flex items-center justify-between"><div><h2 class="text-xl font-bold">Schnellzugriff</h2><p class="text-sm text-slate-500">Ihre wichtigsten Bereiche</p></div></div><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Link v-for="card in cards" :key="card.route" :href="route(card.route)" class="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div class="h-1.5 bg-gradient-to-r" :class="card.tone"></div><div class="p-5"><div class="grid h-11 w-11 place-items-center rounded-xl bg-slate-100 text-xl transition group-hover:bg-slate-950 group-hover:text-white">{{ card.icon }}</div><h3 class="mt-4 font-bold">{{ card.title }}</h3><p class="mt-1 text-sm leading-6 text-slate-500">{{ card.text }}</p><p class="mt-4 text-sm font-semibold text-cyan-700">Öffnen →</p></div></Link></div></section>
 <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><div><h2 class="text-lg font-bold">Meine Projekte</h2><p class="text-sm text-slate-500">Ihre aktuellen Projektteilnahmen</p></div></div><div class="mt-4 grid gap-3 md:grid-cols-2"><article v-for="item in participations" :key="item.id" class="rounded-xl border border-slate-200 p-4"><div class="flex items-start justify-between"><div><p class="font-bold">{{ item.projekt?.name }}</p><p class="mt-1 text-sm text-slate-500">{{ item.standort?.name || 'Kein Standort' }}</p></div><span class="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold capitalize text-emerald-700">{{ item.status }}</span></div></article></div></section></div>
 <aside class="space-y-5"><section class="rounded-2xl border border-amber-200 bg-gradient-to-b from-amber-50 to-white p-5 shadow-sm"><div class="flex items-center justify-between"><div><h2 class="font-bold text-amber-950">Nächste Schritte</h2><p class="text-xs text-amber-700">Aufgaben und Erinnerungen</p></div><span class="rounded-full bg-amber-200 px-2.5 py-1 text-xs font-bold text-amber-900">{{ reminders.length }}</span></div><div v-if="reminders.length" class="mt-4 space-y-3"><Link v-for="item in reminders.slice(0,8)" :key="`${item.type}-${item.title}-${item.at}`" :href="item.href" class="block rounded-xl border border-amber-100 bg-white p-3.5 transition hover:border-amber-300 hover:shadow-sm"><div class="flex justify-between gap-2"><p class="text-sm font-semibold">{{ item.title }}</p><span class="h-fit rounded bg-slate-100 px-2 py-0.5 text-[10px] font-bold text-slate-600">{{ typeLabel[item.type]||'Hinweis' }}</span></div><p class="mt-1 text-xs leading-5 text-slate-500">{{ item.detail }}</p></Link></div><p v-else class="mt-4 rounded-xl bg-white p-4 text-sm text-slate-500">Aktuell stehen keine dringenden Hinweise an.</p></section><Link :href="route('participant-portal.contact.index')" class="block rounded-2xl bg-gradient-to-br from-cyan-600 to-blue-700 p-5 text-white shadow-lg"><p class="text-xs font-bold uppercase tracking-wider text-cyan-100">Konto</p><p class="mt-2 font-bold">Kontaktdaten verwalten</p><p class="mt-1 text-sm text-cyan-100">E-Mail und persönliche Einstellungen prüfen.</p><p class="mt-4 text-sm font-semibold">Öffnen →</p></Link></aside></div>
</ParticipantPortalLayout></template>
