<script setup>
import {computed,reactive,ref} from 'vue';import {Head,Link} from '@inertiajs/vue3';import axios from 'axios';
const props=defineProps({participant:Object,profile:Object,entries:Array,versions:Array,templates:Array,staffMode:{type:Boolean,default:false}});
const items=ref(JSON.parse(JSON.stringify(props.entries||[]))), versions=ref([...(props.versions||[])]), selected=ref(props.templates?.[0]?.key), label=ref(''), query=ref('');
const labels={experience:'Berufserfahrung',education:'Bildung',qualification:'Qualifikation',language:'Sprache',skill:'Kenntnis'};
const blank=()=>({type:'experience',title:'',organization:'',location:'',starts_at:'',ends_at:'',current:false,description:'',proficiency:'',sort_order:items.value.length});const form=reactive(blank());
const routeName=(portal,staff)=>props.staffMode?staff:portal;const personArgs=()=>props.staffMode?[props.participant.id]:[];
const filtered=computed(()=>props.templates.filter(t=>t.name.toLowerCase().includes(query.value.toLowerCase())));
const payload=e=>({...e,organization:e.organization||null,location:e.location||null,starts_at:e.starts_at?.slice(0,10)||null,ends_at:e.current?null:e.ends_at?.slice(0,10)||null,description:e.description||null,proficiency:e.proficiency||null,current:Boolean(e.current),sort_order:Number(e.sort_order)||0});
async function create(){const r=await axios.post(route(routeName('participant-portal.resume.entries.store','teilnehmer.resume.entries.store'),...personArgs()),payload(form));items.value.push(r.data.entry);Object.assign(form,blank())}
async function save(e){const r=await axios.put(route(routeName('participant-portal.resume.entries.update','teilnehmer.resume.entries.update'),e.id),payload(e));Object.assign(e,r.data.entry)}
async function remove(e){if(!confirm('Eintrag wirklich löschen?'))return;await axios.delete(route(routeName('participant-portal.resume.entries.destroy','teilnehmer.resume.entries.destroy'),e.id));items.value=items.value.filter(i=>i.id!==e.id)}
async function createVersion(){const r=await axios.post(route(routeName('participant-portal.resume.versions.store','teilnehmer.resume.versions.store'),...personArgs()),{label:label.value||null,template_key:selected.value});versions.value.unshift(r.data.version);label.value=''}
</script>
<template><Head title="Lebenslauf"/><main class="min-h-screen bg-slate-50 px-4 py-8"><div class="mx-auto max-w-7xl space-y-6"><header class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-widest text-zbb">{{staffMode?'Gemeinsame Bearbeitung':'Teilnehmerportal'}}</p><h1 class="text-3xl font-bold">Lebenslauf von {{participant.vorname}} {{participant.nachname}}</h1><p class="text-sm text-slate-500">Ein gemeinsamer Datenstand für Teilnehmer und Kontaktpersonen</p></div><Link :href="staffMode?route('teilnehmer.edit',participant.id):route('participant-portal.dashboard')" class="rounded-lg border bg-white px-4 py-2">Zurück</Link></header>
<section class="rounded-2xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-semibold">Eintrag hinzufügen</h2><div class="mt-4 grid gap-3 md:grid-cols-3"><select v-model="form.type" class="rounded border-gray-300"><option v-for="(v,k) in labels" :value="k">{{v}}</option></select><input v-model="form.title" placeholder="Bezeichnung" class="rounded border-gray-300"><input v-model="form.organization" placeholder="Organisation / Arbeitgeber" class="rounded border-gray-300"><input v-model="form.location" placeholder="Ort" class="rounded border-gray-300"><input v-model="form.starts_at" type="date" class="rounded border-gray-300"><input v-model="form.ends_at" type="date" :disabled="form.current" class="rounded border-gray-300"><input v-model="form.proficiency" placeholder="Niveau, z. B. B2" class="rounded border-gray-300"><label class="flex items-center gap-2"><input v-model="form.current" type="checkbox"> aktuell</label><textarea v-model="form.description" placeholder="Beschreibung" class="rounded border-gray-300 md:col-span-3"></textarea></div><button class="mt-4 rounded-lg bg-zbb px-4 py-2 text-white" @click="create">Hinzufügen</button></section>
<section class="rounded-2xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-semibold">Einträge</h2><div class="mt-4 space-y-3"><article v-for="e in items" :key="e.id" class="rounded-xl border p-4"><div class="grid gap-3 md:grid-cols-3"><select v-model="e.type" class="rounded border-gray-300"><option v-for="(v,k) in labels" :value="k">{{v}}</option></select><input v-model="e.title" class="rounded border-gray-300"><input v-model="e.organization" class="rounded border-gray-300"><input v-model="e.location" class="rounded border-gray-300"><input v-model="e.starts_at" type="date" class="rounded border-gray-300"><input v-model="e.ends_at" type="date" :disabled="e.current" class="rounded border-gray-300"><input v-model="e.proficiency" class="rounded border-gray-300"><label><input v-model="e.current" type="checkbox"> aktuell</label><textarea v-model="e.description" class="rounded border-gray-300 md:col-span-3"></textarea></div><div class="mt-3 flex gap-4"><button class="font-semibold text-zbb" @click="save(e)">Speichern</button><button class="text-red-600" @click="remove(e)">Löschen</button></div></article><p v-if="!items.length" class="text-slate-500">Noch keine Einträge.</p></div></section>
<section class="rounded-2xl border bg-white p-6 shadow-sm"><div class="flex flex-wrap justify-between gap-3"><div><h2 class="text-lg font-semibold">Design auswählen</h2><p class="text-sm text-slate-500">{{templates.length}} professionelle Layoutvarianten</p></div><input v-model="query" placeholder="Design suchen …" class="rounded-lg border-gray-300"></div><div class="mt-4 grid max-h-96 gap-3 overflow-y-auto pr-2 sm:grid-cols-2 lg:grid-cols-4"><button v-for="t in filtered" :key="t.key" class="rounded-xl border-2 p-3 text-left" :class="selected===t.key?'border-zbb bg-blue-50':'border-slate-200'" @click="selected=t.key"><div class="h-20 rounded bg-white p-2 shadow-inner"><div class="h-3 w-2/3 rounded" :style="{background:t.color}"></div><div class="mt-2 h-1 w-full bg-slate-200"></div><div class="mt-1 h-1 w-4/5 bg-slate-200"></div><div class="mt-3 h-2 w-1/2" :style="{background:t.color}"></div></div><p class="mt-2 text-sm font-semibold">{{t.name}}</p></button></div><div class="mt-5 flex flex-wrap gap-3"><input v-model="label" placeholder="Versionsname, z. B. Bewerbung Firma X" class="min-w-72 flex-1 rounded border-gray-300"><button class="rounded-lg bg-emerald-700 px-5 py-2 text-white" @click="createVersion">Version & PDF anlegen</button></div></section>
<section class="rounded-2xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-semibold">PDF-Versionen</h2><div class="mt-3 space-y-2"><article v-for="v in versions" :key="v.id" class="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><div><b>Version {{v.version}} · {{v.label||'ohne Bezeichnung'}}</b><p class="text-xs text-slate-500">{{v.template_key}} · {{new Date(v.created_at).toLocaleString('de-DE')}}</p></div><div class="flex gap-2"><a target="_blank" :href="route(routeName('participant-portal.resume.versions.print','teilnehmer.resume.versions.print'),v.id)" class="rounded border px-3 py-2 text-sm">Vorschau</a><a :href="route(routeName('participant-portal.resume.versions.download','teilnehmer.resume.versions.download'),v.id)" class="rounded bg-zbb px-3 py-2 text-sm text-white">PDF herunterladen</a></div></article></div></section></div></main></template>
