<?php
namespace Tests\Feature;
use App\Models\AppTask;use App\Models\Berechtigungskategorie;use App\Models\ParticipantApplication;use App\Models\ParticipantPortalDocument;use App\Models\Personen;use App\Models\Projekt;use App\Models\ProjektHasPersonen;use App\Models\Role;use App\Models\RoleDataAccessSetting;use App\Models\Standort;use App\Models\SystemModule;use App\Models\User;use App\Services\Modules\ModuleStateResolver;use Illuminate\Foundation\Testing\RefreshDatabase;use Inertia\Testing\AssertableInertia as Assert;use Spatie\Permission\Models\Permission;use Spatie\Permission\PermissionRegistrar;use Tests\TestCase;
class ParticipantTabConfigurationTest extends TestCase
{
 use RefreshDatabase;
 public function test_current_project_exposes_feature_mapping_and_disabled_portal_data_is_not_sent():void
 {
  $staff=User::factory()->create();$this->grant($staff);app(ModuleStateResolver::class)->set(SystemModule::where('key','participant_portal')->firstOrFail(),true,null,$staff->id);$location=Standort::factory()->create();$project=Projekt::factory()->create(['feature_settings'=>['participant_management'=>true,'attendance_management'=>false,'internship_management'=>false,'completion_management'=>false],'portal_feature_settings'=>['profile'=>false,'attendance_self_service'=>false,'tasks_and_appointments'=>false,'job_search'=>false,'application_management'=>false,'learning'=>false,'messaging'=>false,'consents_and_approvals'=>false]]);$this->assign($project,$staff->person,$location);$staff->update(['current_team_id'=>$project->id]);$participant=Personen::factory()->create(['typ'=>'teilnehmer']);$participation=$this->assign($project,$participant,$location);
  AppTask::query()->create(['owner_user_id'=>$staff->id,'project_id'=>$project->id,'project_person_id'=>$participation->id,'title'=>'Versteckte Aufgabe','status'=>'open','priority'=>'normal','visibility'=>'project']);ParticipantApplication::query()->create(['project_person_id'=>$participation->id,'created_by_user_id'=>$staff->id,'title'=>'Versteckte Bewerbung','status'=>'draft']);ParticipantPortalDocument::query()->create(['project_person_id'=>$participation->id,'uploaded_by_user_id'=>$staff->id,'original_name'=>'intern.pdf','path'=>'fake/intern.pdf','mime_type'=>'application/pdf','size'=>10,'category'=>'other','status'=>'approved','visible_to_participant'=>true]);
  $this->actingAs($staff)->get(route('teilnehmer.edit',$participant))->assertOk()->assertInertia(fn(Assert $page)=>$page->where('currentProjekt.features.attendance_management',false)->where('currentProjekt.features.internship_management',false)->where('currentProjekt.features.completion_management',false)->where('currentProjekt.portal_features.profile',false)->where('currentProjekt.portal_features.tasks_and_appointments',false)->has('participationTasks',0)->has('participationApplications',0)->has('portalDocuments',0)->has('completionChecklist',0)->has('completionReports',0));
 }
 private function assign(Projekt $p,Personen $person,Standort $s):ProjektHasPersonen{return ProjektHasPersonen::query()->create(['projekt_id'=>$p->id,'personen_id'=>$person->id,'standort_id'=>$s->id,'status'=>'aktiv']);}
 private function grant(User $u):void{$c=Berechtigungskategorie::query()->firstOrCreate(['name'=>'Tab-Konfiguration'],['beschreibung'=>'']);Permission::query()->updateOrCreate(['name'=>'teilnehmer.update','guard_name'=>'web'],['berechtigungskategorie_id'=>$c->id,'beschreibung'=>null]);app(PermissionRegistrar::class)->forgetCachedPermissions();$r=Role::query()->create(['name'=>'Tabs-'.uniqid(),'guard_name'=>'web','color'=>'#123456']);RoleDataAccessSetting::query()->create(['role_id'=>$r->id,'team_scope'=>'own_projects','participant_scope'=>'all']);$u->assignRole($r);$u->givePermissionTo('teilnehmer.update');}
}
