<?php
namespace Tests\Feature;
use App\Models\Berechtigungskategorie;use App\Models\ParticipantJobRecommendation;use App\Models\Personen;use App\Models\Projekt;use App\Models\ProjektHasPersonen;use App\Models\Role;use App\Models\RoleDataAccessSetting;use App\Models\Standort;use App\Models\SystemModule;use App\Models\User;use App\Services\Modules\ModuleStateResolver;use Illuminate\Foundation\Testing\RefreshDatabase;use Spatie\Permission\Models\Permission;use Spatie\Permission\PermissionRegistrar;use Tests\TestCase;
class ParticipantJobRecommendationTest extends TestCase
{
 use RefreshDatabase;
 public function test_staff_recommendation_can_be_viewed_and_converted_only_by_own_participant():void
 {
  $staff=User::factory()->create();$this->grant($staff);app(ModuleStateResolver::class)->set(SystemModule::where('key','participant_portal')->firstOrFail(),true,null,$staff->id);$location=Standort::factory()->create();$project=Projekt::factory()->create(['portal_feature_settings'=>['job_search'=>true,'application_management'=>true]]);$this->assign($project,$staff->person,$location);$staff->update(['current_team_id'=>$project->id]);$participant=Personen::factory()->create(['typ'=>'teilnehmer']);$participation=$this->assign($project,$participant,$location);$portal=User::factory()->create(['person_id'=>$participant->id]);
  $created=$this->actingAs($staff)->postJson(route('teilnehmer.recommendations.store',$participation),['external_ref'=>'REC-1','title'=>'Fachlagerist/in','employer'=>'Beispiel GmbH','location'=>'Saarbrücken','source_url'=>'https://example.test/job/1','note'=>'Passt zu den bisherigen Erfahrungen.'])->assertCreated()->assertJsonPath('recommendation.title','Fachlagerist/in');$recommendation=ParticipantJobRecommendation::findOrFail($created->json('recommendation.id'));
  $other=Personen::factory()->create(['typ'=>'teilnehmer']);$otherPortal=User::factory()->create(['person_id'=>$other->id]);$this->actingAs($otherPortal)->postJson(route('participant-portal.recommendations.convert',$recommendation))->assertNotFound();
  $this->actingAs($portal)->putJson(route('participant-portal.recommendations.viewed',$recommendation))->assertOk();$this->assertNotNull($recommendation->fresh()->viewed_at);
  $converted=$this->actingAs($portal)->postJson(route('participant-portal.recommendations.convert',$recommendation))->assertCreated()->assertJsonPath('application.status','draft');$this->assertDatabaseHas('participant_applications',['id'=>$converted->json('application.id'),'project_person_id'=>$participation->id,'external_ref'=>'REC-1']);$this->assertNotNull($recommendation->fresh()->converted_application_id);$this->actingAs($portal)->postJson(route('participant-portal.recommendations.convert',$recommendation))->assertUnprocessable();
 }
 public function test_disabled_project_feature_blocks_recommendations():void
 {
  $staff=User::factory()->create();$this->grant($staff);app(ModuleStateResolver::class)->set(SystemModule::where('key','participant_portal')->firstOrFail(),true,null,$staff->id);$location=Standort::factory()->create();$project=Projekt::factory()->create(['portal_feature_settings'=>['job_search'=>false,'application_management'=>false]]);$this->assign($project,$staff->person,$location);$staff->update(['current_team_id'=>$project->id]);$participant=Personen::factory()->create(['typ'=>'teilnehmer']);$participation=$this->assign($project,$participant,$location);$this->actingAs($staff)->postJson(route('teilnehmer.recommendations.store',$participation),['title'=>'Nicht erlaubt'])->assertNotFound();$this->assertDatabaseCount('participant_job_recommendations',0);
 }
 private function assign(Projekt $p,Personen $person,Standort $s):ProjektHasPersonen{return ProjektHasPersonen::query()->create(['projekt_id'=>$p->id,'personen_id'=>$person->id,'standort_id'=>$s->id,'status'=>'aktiv']);}
 private function grant(User $u):void{$c=Berechtigungskategorie::query()->firstOrCreate(['name'=>'Empfehlungen'],['beschreibung'=>'']);Permission::query()->updateOrCreate(['name'=>'teilnehmer.update','guard_name'=>'web'],['berechtigungskategorie_id'=>$c->id,'beschreibung'=>null]);app(PermissionRegistrar::class)->forgetCachedPermissions();$r=Role::query()->create(['name'=>'Recommendation-'.uniqid(),'guard_name'=>'web','color'=>'#123456']);RoleDataAccessSetting::query()->create(['role_id'=>$r->id,'team_scope'=>'own_projects','participant_scope'=>'all']);$u->assignRole($r);$u->givePermissionTo('teilnehmer.update');}
}
