<?php
namespace Tests\Feature;
use App\Models\Berechtigungskategorie;use App\Models\ParticipantApplication;use App\Models\ParticipantPortalDocument;use App\Models\Personen;use App\Models\Projekt;use App\Models\ProjektHasPersonen;use App\Models\Role;use App\Models\RoleDataAccessSetting;use App\Models\Standort;use App\Models\SystemModule;use App\Models\User;use App\Services\Modules\ModuleStateResolver;use Illuminate\Foundation\Testing\RefreshDatabase;use Spatie\Permission\Models\Permission;use Spatie\Permission\PermissionRegistrar;use Tests\TestCase;
class ParticipantApplicationPackageTest extends TestCase
{
 use RefreshDatabase;
 public function test_approved_documents_form_a_dual_approved_participation_bound_package():void
 {
  $staff=User::factory()->create();$this->grant($staff);app(ModuleStateResolver::class)->set(SystemModule::where('key','participant_portal')->firstOrFail(),true,null,$staff->id);$location=Standort::factory()->create();$project=Projekt::factory()->create(['portal_feature_settings'=>['application_management'=>true]]);$this->assign($project,$staff->person,$location);$staff->update(['current_team_id'=>$project->id]);$participant=Personen::factory()->create(['typ'=>'teilnehmer']);$participation=$this->assign($project,$participant,$location);$portal=User::factory()->create(['person_id'=>$participant->id]);$application=ParticipantApplication::query()->create(['project_person_id'=>$participation->id,'created_by_user_id'=>$portal->id,'title'=>'Ausbildung','status'=>'draft']);$document=$this->document($participation,$portal,true,'approved');
  $this->actingAs($portal)->putJson(route('participant-portal.applications.documents.sync',$application),['document_ids'=>[$document->id]])->assertOk()->assertJsonCount(1,'application.documents');$this->actingAs($portal)->postJson(route('participant-portal.applications.package.approve',$application))->assertOk();$this->assertNotNull($application->fresh()->participant_package_approved_at);$this->assertNull($application->fresh()->staff_package_approved_at);
  $this->actingAs($staff)->postJson(route('teilnehmer.applications.package.approve',$application))->assertOk();$fresh=$application->fresh();$this->assertNotNull($fresh->staff_package_approved_at);$this->assertSame($staff->id,$fresh->staff_package_approved_by_user_id);
  $this->actingAs($portal)->putJson(route('participant-portal.applications.documents.sync',$application),['document_ids'=>[]])->assertOk();$fresh=$application->fresh();$this->assertNull($fresh->participant_package_approved_at);$this->assertNull($fresh->staff_package_approved_at);
 }
 public function test_foreign_unapproved_or_hidden_documents_cannot_enter_participant_package():void
 {
  $staff=User::factory()->create();$this->grant($staff);app(ModuleStateResolver::class)->set(SystemModule::where('key','participant_portal')->firstOrFail(),true,null,$staff->id);$location=Standort::factory()->create();$project=Projekt::factory()->create(['portal_feature_settings'=>['application_management'=>true]]);$this->assign($project,$staff->person,$location);$staff->update(['current_team_id'=>$project->id]);$participant=Personen::factory()->create(['typ'=>'teilnehmer']);$participation=$this->assign($project,$participant,$location);$portal=User::factory()->create(['person_id'=>$participant->id]);$application=ParticipantApplication::query()->create(['project_person_id'=>$participation->id,'created_by_user_id'=>$portal->id,'title'=>'Bewerbung','status'=>'draft']);$pending=$this->document($participation,$portal,true,'pending');$hidden=$this->document($participation,$staff,false,'approved');$this->actingAs($portal)->putJson(route('participant-portal.applications.documents.sync',$application),['document_ids'=>[$pending->id]])->assertUnprocessable();$this->actingAs($portal)->putJson(route('participant-portal.applications.documents.sync',$application),['document_ids'=>[$hidden->id]])->assertUnprocessable();$this->assertDatabaseCount('participant_application_documents',0);
 }
 private function document(ProjektHasPersonen $p,User $u,bool $visible,string $status):ParticipantPortalDocument{return ParticipantPortalDocument::query()->create(['project_person_id'=>$p->id,'uploaded_by_user_id'=>$u->id,'original_name'=>uniqid().'.pdf','path'=>'fake/'.uniqid().'.pdf','mime_type'=>'application/pdf','size'=>100,'category'=>'application','status'=>$status,'visible_to_participant'=>$visible]);}
 private function assign(Projekt $p,Personen $person,Standort $s):ProjektHasPersonen{return ProjektHasPersonen::query()->create(['projekt_id'=>$p->id,'personen_id'=>$person->id,'standort_id'=>$s->id,'status'=>'aktiv']);}
 private function grant(User $u):void{$c=Berechtigungskategorie::query()->firstOrCreate(['name'=>'Bewerbungspaket'],['beschreibung'=>'']);Permission::query()->updateOrCreate(['name'=>'teilnehmer.update','guard_name'=>'web'],['berechtigungskategorie_id'=>$c->id,'beschreibung'=>null]);app(PermissionRegistrar::class)->forgetCachedPermissions();$r=Role::query()->create(['name'=>'Package-'.uniqid(),'guard_name'=>'web','color'=>'#123456']);RoleDataAccessSetting::query()->create(['role_id'=>$r->id,'team_scope'=>'own_projects','participant_scope'=>'all']);$u->assignRole($r);$u->givePermissionTo('teilnehmer.update');}
}
