<?php
namespace Tests\Feature;
use App\Models\ParticipantApplication;use App\Models\Personen;use App\Models\Projekt;use App\Models\ProjektHasPersonen;use App\Models\Standort;use App\Models\SystemModule;use App\Models\User;use App\Services\Modules\ModuleStateResolver;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Http\Client\Request;use Illuminate\Support\Facades\Http;use Illuminate\Support\Facades\Mail;use Tests\TestCase;
class ParticipantCareerStudioTest extends TestCase {use RefreshDatabase;
 public function test_participant_creates_multiple_documents_links_and_sends_application():void {Mail::fake();[$portal,$application]=$this->context();$templates=app(\App\Services\CvTemplateCatalog::class)->keys();$this->assertGreaterThanOrEqual(200,count($templates));$template=$templates[0];$base=['full_name'=>'Mina Muster','headline'=>'Pflegefachkraft','contact'=>'mina@example.test','summary'=>'Zuverlässig','entries'=>[]];
  $resume=$this->actingAs($portal)->postJson(route('participant-portal.career-studio.store'),['type'=>'resume','title'=>'CV Pflege','template_key'=>$template,'content'=>$base,'is_default'=>true])->assertCreated()->json('document');
  $letter=$this->actingAs($portal)->postJson(route('participant-portal.career-studio.store'),['type'=>'cover_letter','title'=>'Anschreiben Klinik','template_key'=>$template,'content'=>[...$base,'recipient'=>'Klinik GmbH','subject'=>'Bewerbung','body'=>'Sehr geehrte Damen und Herren'],'is_default'=>false])->assertCreated()->json('document');
  $this->actingAs($portal)->postJson(route('participant-portal.career-studio.duplicate',$resume['id']))->assertCreated();$this->assertDatabaseCount('participant_career_documents',3);
  $this->actingAs($portal)->putJson(route('participant-portal.applications.career-documents.sync',$application),['document_ids'=>[$letter['id'],$resume['id']]])->assertOk()->assertJsonCount(2,'application.career_documents');
  $this->actingAs($portal)->postJson(route('participant-portal.applications.notes.store',$application),['body'=>'Telefonat am Montag'])->assertCreated();
  $this->actingAs($portal)->postJson(route('participant-portal.applications.send',$application),['to'=>'jobs@klinik.test','subject'=>'Bewerbung Pflege','message'=>'Anbei meine Unterlagen.'])->assertOk()->assertJsonPath('application.status','sent');
  $fresh=$application->fresh();$this->assertSame('jobs@klinik.test',$fresh->recipient_email);$this->assertNotNull($fresh->last_sent_at);$this->assertDatabaseHas('participant_application_activities',['application_id'=>$application->id,'type'=>'email_sent']);Mail::assertSentCount(1);
 }
 public function test_foreign_document_cannot_be_linked():void {[$portal,$application]=$this->context();$other=Personen::factory()->create(['typ'=>'teilnehmer']);$doc=\App\Models\ParticipantCareerDocument::create(['person_id'=>$other->id,'type'=>'resume','title'=>'Fremd','template_key'=>'classic-navy-sans','content'=>[]]);$this->actingAs($portal)->putJson(route('participant-portal.applications.career-documents.sync',$application),['document_ids'=>[$doc->id]])->assertUnprocessable();}
 public function test_participant_generates_a_cover_letter_from_own_application_context():void {[$portal,$application]=$this->context();config()->set('services.zbb_ai_agent',['base_url'=>'http://127.0.0.1:18000','key_id'=>'laravel','secret'=>'test-secret-that-is-at-least-32-bytes-long','connect_timeout'=>3,'timeout'=>130,'max_response_bytes'=>1000000]);Http::preventStrayRequests();Http::fake(function(Request $request){$payload=$request->data();$this->assertSame('cover_letter',$payload['task']);$this->assertContains('job-description',array_column($payload['sources'],'source_id'));return Http::response(['run_id'=>$payload['run_id'],'task'=>'cover_letter','title'=>'Anschreiben','content'=>'Sehr geehrte Damen und Herren,\n\nmein geprüfter Entwurf.','citations'=>[],'warnings'=>[]]);});$this->actingAs($portal)->postJson(route('participant-portal.career-studio.ai-cover-letter'),['application_id'=>$application->id,'job_description'=>'Gesucht wird eine zuverlässige Pflegefachkraft.','tone'=>'professional'])->assertOk()->assertJsonPath('task','cover_letter')->assertJsonPath('content','Sehr geehrte Damen und Herren,\n\nmein geprüfter Entwurf.');}
 private function context():array{$person=Personen::factory()->create(['typ'=>'teilnehmer','aktiv'=>true]);$portal=User::factory()->create(['person_id'=>$person->id]);app(ModuleStateResolver::class)->set(SystemModule::where('key','participant_portal')->firstOrFail(),true,null,$portal->id);$project=Projekt::factory()->create(['portal_feature_settings'=>['profile'=>true,'application_management'=>true]]);$location=Standort::factory()->create();$participation=ProjektHasPersonen::create(['projekt_id'=>$project->id,'personen_id'=>$person->id,'standort_id'=>$location->id,'status'=>'aktiv']);$application=ParticipantApplication::create(['project_person_id'=>$participation->id,'created_by_user_id'=>$portal->id,'title'=>'Pflegefachkraft','employer'=>'Klinik','status'=>'draft']);return[$portal,$application];}
}
