<?php
namespace Tests\Feature;
use App\Models\Berechtigungskategorie;use App\Models\ParticipantConsentEvent;use App\Models\Personen;use App\Models\ProjectConsentDefinition;use App\Models\Projekt;use App\Models\ProjektHasPersonen;use App\Models\Role;use App\Models\RoleDataAccessSetting;use App\Models\Standort;use App\Models\SystemModule;use App\Models\User;use App\Services\Modules\ModuleStateResolver;use Illuminate\Foundation\Testing\RefreshDatabase;use Spatie\Permission\Models\Permission;use Spatie\Permission\PermissionRegistrar;use Tests\TestCase;
class ParticipantConsentTest extends TestCase
{
 use RefreshDatabase;
 public function test_definition_versions_acceptance_and_withdrawal_are_immutable_and_project_bound():void
 {
  $staff=User::factory()->create();$this->grant($staff);app(ModuleStateResolver::class)->set(SystemModule::where('key','participant_portal')->firstOrFail(),true,null,$staff->id);$location=Standort::factory()->create();$project=Projekt::factory()->create(['portal_feature_settings'=>['consents_and_approvals'=>true]]);$this->assign($project,$staff->person,$location);$staff->update(['current_team_id'=>$project->id]);
  $created=$this->actingAs($staff)->postJson(route('projekt.consents.store',$project),['key'=>'foto_freigabe','title'=>'Foto-Freigabe','purpose'=>'Dokumentation der Maßnahme','content'=>'Ich erlaube die projektbezogene Verwendung.','required'=>false,'allow_withdrawal'=>true,'active'=>true,'sort_order'=>1])->assertCreated();$definition=ProjectConsentDefinition::findOrFail($created->json('definition.id'));
  $participant=Personen::factory()->create(['typ'=>'teilnehmer']);$participation=$this->assign($project,$participant,$location);$portal=User::factory()->create(['person_id'=>$participant->id]);
  $accepted=$this->actingAs($portal)->postJson(route('participant-portal.consents.act',$definition),['project_person_id'=>$participation->id,'action'=>'accepted','confirmed'=>true])->assertCreated()->assertJsonPath('event.action','accepted');$event=ParticipantConsentEvent::findOrFail($accepted->json('event.id'));$this->assertSame(hash('sha256',$definition->content),$event->content_sha256);$this->assertSame(1,$event->definition_version);
  $this->actingAs($portal)->postJson(route('participant-portal.consents.act',$definition),['project_person_id'=>$participation->id,'action'=>'withdrawn','confirmed'=>true])->assertCreated()->assertJsonPath('event.action','withdrawn');
  $revised=$this->actingAs($staff)->postJson(route('projekt.consents.revise',$definition),['title'=>'Foto-Freigabe neu','purpose'=>'Neuer klarer Zweck','content'=>'Neue Fassung der Einwilligung.','required'=>true,'allow_withdrawal'=>true,'active'=>true,'sort_order'=>1])->assertOk();$this->assertSame(2,$revised->json('definition.version'));$this->assertDatabaseHas('participant_consent_events',['id'=>$event->id,'definition_version'=>1,'content_sha256'=>hash('sha256','Ich erlaube die projektbezogene Verwendung.')]);
 }
 public function test_disabled_feature_and_foreign_participation_are_rejected():void
 {
  $staff=User::factory()->create();$this->grant($staff);app(ModuleStateResolver::class)->set(SystemModule::where('key','participant_portal')->firstOrFail(),true,null,$staff->id);$location=Standort::factory()->create();$project=Projekt::factory()->create(['portal_feature_settings'=>['consents_and_approvals'=>false]]);$this->assign($project,$staff->person,$location);$staff->update(['current_team_id'=>$project->id]);$participant=Personen::factory()->create(['typ'=>'teilnehmer']);$participation=$this->assign($project,$participant,$location);$portal=User::factory()->create(['person_id'=>$participant->id]);$definition=ProjectConsentDefinition::query()->create(['project_id'=>$project->id,'key'=>'privacy','version'=>1,'title'=>'Datenschutz','purpose'=>'Zweck','content'=>'Text','required'=>true,'allow_withdrawal'=>true,'active'=>true,'sort_order'=>0]);
  $this->actingAs($portal)->postJson(route('participant-portal.consents.act',$definition),['project_person_id'=>$participation->id,'action'=>'accepted','confirmed'=>true])->assertNotFound();$project->update(['portal_feature_settings'=>['consents_and_approvals'=>true]]);$other=Personen::factory()->create(['typ'=>'teilnehmer']);$otherPortal=User::factory()->create(['person_id'=>$other->id]);$this->actingAs($otherPortal)->postJson(route('participant-portal.consents.act',$definition),['project_person_id'=>$participation->id,'action'=>'accepted','confirmed'=>true])->assertNotFound();$this->assertDatabaseCount('participant_consent_events',0);
 }
 private function assign(Projekt $p,Personen $person,Standort $s):ProjektHasPersonen{return ProjektHasPersonen::query()->create(['projekt_id'=>$p->id,'personen_id'=>$person->id,'standort_id'=>$s->id,'status'=>'aktiv']);}
 private function grant(User $u):void{$c=Berechtigungskategorie::query()->firstOrCreate(['name'=>'Einwilligungen'],['beschreibung'=>'']);Permission::query()->updateOrCreate(['name'=>'projekt.update','guard_name'=>'web'],['berechtigungskategorie_id'=>$c->id,'beschreibung'=>null]);app(PermissionRegistrar::class)->forgetCachedPermissions();$r=Role::query()->create(['name'=>'Consent-'.uniqid(),'guard_name'=>'web','color'=>'#123456']);RoleDataAccessSetting::query()->create(['role_id'=>$r->id,'team_scope'=>'own_projects','participant_scope'=>'all']);$u->assignRole($r);$u->givePermissionTo('projekt.update');}
}
