<?php
namespace Tests\Feature;
use App\Models\Berechtigungskategorie;use App\Models\Personen;use App\Models\PortalCourse;use App\Models\PortalCourseEnrollment;use App\Models\PortalCourseQuiz;use App\Models\Projekt;use App\Models\ProjektHasPersonen;use App\Models\Role;use App\Models\RoleDataAccessSetting;use App\Models\Standort;use App\Models\SystemModule;use App\Models\User;use App\Services\Modules\ModuleStateResolver;use Illuminate\Foundation\Testing\RefreshDatabase;use Inertia\Testing\AssertableInertia as Assert;use Spatie\Permission\Models\Permission;use Spatie\Permission\PermissionRegistrar;use Tests\TestCase;
class PortalCourseQuizTest extends TestCase
{
 use RefreshDatabase;
 public function test_quiz_answers_are_hidden_and_attempts_are_scored_with_limit():void
 {
  $staff=User::factory()->create();$this->grant($staff);app(ModuleStateResolver::class)->set(SystemModule::where('key','participant_portal')->firstOrFail(),true,null,$staff->id);$location=Standort::factory()->create();$project=Projekt::factory()->create(['portal_feature_settings'=>['learning'=>true]]);$this->assign($project,$staff->person,$location);$staff->update(['current_team_id'=>$project->id]);$participant=Personen::factory()->create(['typ'=>'teilnehmer']);$participation=$this->assign($project,$participant,$location);$portal=User::factory()->create(['person_id'=>$participant->id]);$course=PortalCourse::query()->create(['project_id'=>$project->id,'created_by_user_id'=>$staff->id,'title'=>'Grundlagen','status'=>'published','self_enrollment'=>false]);PortalCourseEnrollment::query()->create(['course_id'=>$course->id,'project_person_id'=>$participation->id,'status'=>'enrolled','enrolled_at'=>now()]);
  $quizResponse=$this->actingAs($staff)->postJson(route('projekt.courses.quizzes.store',$course),['lesson_id'=>null,'title'=>'Abschlusstest','description'=>'Kurzer Test','passing_percent'=>60,'max_attempts'=>2,'published'=>true,'sort_order'=>0])->assertCreated();$quiz=PortalCourseQuiz::findOrFail($quizResponse->json('quiz.id'));
  $questionResponse=$this->actingAs($staff)->postJson(route('projekt.courses.quizzes.questions.store',$quiz),['question'=>'Welche Antwort ist richtig?','type'=>'single','points'=>5,'sort_order'=>0,'options'=>[['label'=>'Falsch','is_correct'=>false],['label'=>'Richtig','is_correct'=>true]]])->assertCreated();$questionId=$questionResponse->json('question.id');$wrongId=$questionResponse->json('question.options.0.id');$correctId=$questionResponse->json('question.options.1.id');
  $this->actingAs($portal)->get(route('participant-portal.learning.quizzes.index'))->assertOk()->assertInertia(fn(Assert $page)=>$page->component('ParticipantPortal/Quizzes')->has('quizzes',1)->missing('quizzes.0.questions.0.options.0.is_correct'));
  $this->actingAs($portal)->postJson(route('participant-portal.learning.quizzes.submit',$quiz),['answers'=>[$questionId=>[$wrongId]]])->assertCreated()->assertJsonPath('attempt.percentage','0.00')->assertJsonPath('attempt.passed',false);
  $this->actingAs($portal)->postJson(route('participant-portal.learning.quizzes.submit',$quiz),['answers'=>[$questionId=>[$correctId]]])->assertCreated()->assertJsonPath('attempt.percentage','100.00')->assertJsonPath('attempt.passed',true);
  $this->actingAs($portal)->postJson(route('participant-portal.learning.quizzes.submit',$quiz),['answers'=>[$questionId=>[$correctId]]])->assertUnprocessable();$this->assertDatabaseCount('portal_quiz_attempts',2);$this->assertDatabaseHas('portal_quiz_answers',['question_id'=>$questionId,'correct'=>1,'earned_points'=>5]);
  $other=Personen::factory()->create(['typ'=>'teilnehmer']);$otherPortal=User::factory()->create(['person_id'=>$other->id]);$this->actingAs($otherPortal)->postJson(route('participant-portal.learning.quizzes.submit',$quiz),['answers'=>[$questionId=>[$correctId]]])->assertNotFound();
 }
 public function test_unpublished_quiz_and_foreign_options_are_rejected():void
 {
  $staff=User::factory()->create();$this->grant($staff);app(ModuleStateResolver::class)->set(SystemModule::where('key','participant_portal')->firstOrFail(),true,null,$staff->id);$location=Standort::factory()->create();$project=Projekt::factory()->create(['portal_feature_settings'=>['learning'=>true]]);$this->assign($project,$staff->person,$location);$staff->update(['current_team_id'=>$project->id]);$participant=Personen::factory()->create(['typ'=>'teilnehmer']);$participation=$this->assign($project,$participant,$location);$portal=User::factory()->create(['person_id'=>$participant->id]);$course=PortalCourse::query()->create(['project_id'=>$project->id,'created_by_user_id'=>$staff->id,'title'=>'Kurs','status'=>'published','self_enrollment'=>false]);PortalCourseEnrollment::query()->create(['course_id'=>$course->id,'project_person_id'=>$participation->id,'status'=>'enrolled','enrolled_at'=>now()]);$quiz=$course->quizzes()->create(['title'=>'Entwurf','passing_percent'=>50,'max_attempts'=>1,'published'=>false,'sort_order'=>0]);$this->actingAs($portal)->postJson(route('participant-portal.learning.quizzes.submit',$quiz),['answers'=>[]])->assertNotFound();
 }
 private function assign(Projekt $p,Personen $person,Standort $s):ProjektHasPersonen{return ProjektHasPersonen::query()->create(['projekt_id'=>$p->id,'personen_id'=>$person->id,'standort_id'=>$s->id,'status'=>'aktiv']);}
 private function grant(User $u):void{$c=Berechtigungskategorie::query()->firstOrCreate(['name'=>'Quiz'],['beschreibung'=>'']);Permission::query()->updateOrCreate(['name'=>'projekt.update','guard_name'=>'web'],['berechtigungskategorie_id'=>$c->id,'beschreibung'=>null]);app(PermissionRegistrar::class)->forgetCachedPermissions();$r=Role::query()->create(['name'=>'Quiz-'.uniqid(),'guard_name'=>'web','color'=>'#123456']);RoleDataAccessSetting::query()->create(['role_id'=>$r->id,'team_scope'=>'own_projects','participant_scope'=>'all']);$u->assignRole($r);$u->givePermissionTo('projekt.update');}
}
