<?php
namespace Tests\Feature;
use App\Models\Anwesenheitsstatuten;use App\Models\AppCalendarEvent;use App\Models\Bereich;use App\Models\Berechtigungskategorie;use App\Models\Gruppe;use App\Models\GruppeHasPersonen;use App\Models\Personen;use App\Models\Projekt;use App\Models\ProjektHasPersonen;use App\Models\Raeume;use App\Models\Role;use App\Models\RoleDataAccessSetting;use App\Models\Standort;use App\Models\SystemModule;use App\Models\Tage;use App\Models\User;use App\Models\Zeiten;use App\Services\Modules\ModuleStateResolver;use Illuminate\Foundation\Testing\RefreshDatabase;use Spatie\Permission\Models\Permission;use Spatie\Permission\PermissionRegistrar;use Tests\TestCase;
class PortalAttendanceSelfServiceTest extends TestCase
{
 use RefreshDatabase;
 public function test_read_only_attendance_calendar_and_correction_resolution_are_project_bound():void
 {
  $staff=User::factory()->create();$this->grant($staff);app(ModuleStateResolver::class)->set(SystemModule::where('key','participant_portal')->firstOrFail(),true,null,$staff->id);$location=Standort::factory()->create();$project=Projekt::factory()->create(['portal_feature_settings'=>['attendance_self_service'=>true,'tasks_and_appointments'=>true]]);$this->assign($project,$staff->person,$location);$staff->update(['current_team_id'=>$project->id]);$participant=Personen::factory()->create(['typ'=>'teilnehmer']);$this->assign($project,$participant,$location);$portal=User::factory()->create(['person_id'=>$participant->id]);
  $status=Anwesenheitsstatuten::query()->create(['status'=>'unentschuldigt','farben'=>'#ef4444','abkuerzung'=>'U']);$bereich=Bereich::query()->create(['name'=>'Garten']);$room=Raeume::query()->create(['name'=>'Raum','standort_id'=>$location->id,'typ'=>'Seminarraum','aktiv'=>true]);$group=Gruppe::query()->create(['personen_id'=>$staff->person_id,'bereich_id'=>$bereich->id,'projekt_id'=>$project->id,'standort_id'=>$location->id,'raum_id'=>$room->id]);$day=Tage::query()->create(['datum'=>'2026-07-06','wochentag'=>'Montag']);$time=Zeiten::query()->create(['startzeit'=>'08:00','endzeit'=>'16:00']);$attendance=GruppeHasPersonen::query()->create(['personen_id'=>$participant->id,'user_id'=>$staff->person_id,'gruppe_id'=>$group->id,'tage_id'=>$day->id,'zeitgeplant_id'=>$time->id,'zeittatsaechlich_id'=>$time->id,'anwesenheitsstatuten_id'=>$status->id]);
  AppCalendarEvent::query()->create(['owner_user_id'=>$staff->id,'project_id'=>$project->id,'title'=>'Beratung','starts_at'=>now()->addDay(),'visibility'=>'project']);
  $this->actingAs($portal)->get(route('participant-portal.self-service.index'))->assertOk()->assertInertia(fn($page)=>$page->has('attendance',1)->has('events',1)->where('attendance.0.id',$attendance->id));
  $correctionResponse=$this->postJson(route('participant-portal.attendance.corrections.store',$attendance),['message'=>'Ich war an diesem Tag entschuldigt.'])->assertCreated();$id=$correctionResponse->json('correction.id');
  $this->postJson(route('participant-portal.attendance.corrections.store',$attendance),['message'=>'Noch eine Anfrage'])->assertUnprocessable();
  $this->actingAs($staff)->putJson(route('teilnehmer.attendance.corrections.resolve',$id),['status'=>'accepted','resolution_note'=>'Nachweis wurde geprüft.'])->assertOk()->assertJsonPath('correction.status','accepted');
  $this->assertDatabaseHas('attendance_correction_requests',['id'=>$id,'status'=>'accepted','resolved_by_user_id'=>$staff->id]);
 }
 private function assign(Projekt $p,Personen $person,Standort $s):ProjektHasPersonen{return ProjektHasPersonen::query()->create(['projekt_id'=>$p->id,'personen_id'=>$person->id,'standort_id'=>$s->id,'status'=>'aktiv']);}
 private function grant(User $u):void{$c=Berechtigungskategorie::query()->firstOrCreate(['name'=>'Korrekturen'],['beschreibung'=>'']);Permission::query()->updateOrCreate(['name'=>'teilnehmer.update','guard_name'=>'web'],['berechtigungskategorie_id'=>$c->id,'beschreibung'=>null]);app(PermissionRegistrar::class)->forgetCachedPermissions();$r=Role::query()->create(['name'=>'Korrektur-'.uniqid(),'guard_name'=>'web','color'=>'#123456']);RoleDataAccessSetting::query()->create(['role_id'=>$r->id,'team_scope'=>'own_projects','participant_scope'=>'all']);$u->assignRole($r);$u->givePermissionTo('teilnehmer.update');}
}
