<?php
namespace Tests\Feature;
use App\Models\Berechtigungskategorie;use App\Models\Personen;use App\Models\PortalCourse;use App\Models\PortalCourseAssignment;use App\Models\PortalCourseEnrollment;use App\Models\Projekt;use App\Models\ProjektHasPersonen;use App\Models\Role;use App\Models\RoleDataAccessSetting;use App\Models\Standort;use App\Models\SystemModule;use App\Models\User;use App\Services\Modules\ModuleStateResolver;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Http\UploadedFile;use Illuminate\Support\Facades\Storage;use Spatie\Permission\Models\Permission;use Spatie\Permission\PermissionRegistrar;use Tests\TestCase;
class PortalLearningContentTest extends TestCase
{
 use RefreshDatabase;
 public function test_material_assignment_submission_and_review_are_enrollment_bound():void
 {
  Storage::fake('local');$staff=User::factory()->create();$this->grant($staff);app(ModuleStateResolver::class)->set(SystemModule::where('key','participant_portal')->firstOrFail(),true,null,$staff->id);$location=Standort::factory()->create();$project=Projekt::factory()->create(['portal_feature_settings'=>['learning'=>true]]);$this->assign($project,$staff->person,$location);$staff->update(['current_team_id'=>$project->id]);$participant=Personen::factory()->create(['typ'=>'teilnehmer']);$participation=$this->assign($project,$participant,$location);$portal=User::factory()->create(['person_id'=>$participant->id]);$course=PortalCourse::query()->create(['project_id'=>$project->id,'created_by_user_id'=>$staff->id,'title'=>'Bewerbungstraining','status'=>'published','self_enrollment'=>false]);$enrollment=PortalCourseEnrollment::query()->create(['course_id'=>$course->id,'project_person_id'=>$participation->id,'status'=>'enrolled','enrolled_at'=>now()]);
  $materialResponse=$this->actingAs($staff)->post(route('projekt.courses.materials.store',$course),['title'=>'Arbeitsblatt','published'=>1,'sort_order'=>0,'file'=>UploadedFile::fake()->create('arbeitsblatt.pdf',100,'application/pdf')])->assertCreated();$materialId=$materialResponse->json('material.id');$this->actingAs($portal)->get(route('participant-portal.learning.materials.download',$materialId))->assertOk();
  $assignmentResponse=$this->actingAs($staff)->postJson(route('projekt.courses.assignments.store',$course),['lesson_id'=>null,'title'=>'Anschreiben erstellen','instructions'=>'Erstellen Sie einen Entwurf.','due_at'=>now()->addWeek()->toISOString(),'max_points'=>10,'allow_text'=>true,'allow_file'=>true,'published'=>true,'sort_order'=>0])->assertCreated();$assignment=PortalCourseAssignment::findOrFail($assignmentResponse->json('assignment.id'));
  $submissionResponse=$this->actingAs($portal)->post(route('participant-portal.learning.assignments.submit',$assignment),['text_answer'=>'Mein Entwurf','file'=>UploadedFile::fake()->create('entwurf.docx',50,'application/vnd.openxmlformats-officedocument.wordprocessingml.document')])->assertCreated();$submissionId=$submissionResponse->json('submission.id');$this->assertDatabaseHas('portal_course_submissions',['id'=>$submissionId,'enrollment_id'=>$enrollment->id,'status'=>'submitted']);$this->actingAs($portal)->get(route('participant-portal.learning.submissions.download',$submissionId))->assertOk();
  $this->actingAs($staff)->putJson(route('projekt.courses.submissions.review',$submissionId),['status'=>'reviewed','score'=>8.5,'feedback'=>'Guter Aufbau.'])->assertOk()->assertJsonPath('submission.status','reviewed')->assertJsonPath('submission.score','8.50');$this->actingAs($staff)->putJson(route('projekt.courses.submissions.review',$submissionId),['status'=>'reviewed','score'=>11,'feedback'=>'Zu viele Punkte'])->assertUnprocessable();
  $other=Personen::factory()->create(['typ'=>'teilnehmer']);$otherPortal=User::factory()->create(['person_id'=>$other->id]);$this->actingAs($otherPortal)->get(route('participant-portal.learning.materials.download',$materialId))->assertNotFound();$this->actingAs($otherPortal)->postJson(route('participant-portal.learning.assignments.submit',$assignment),['text_answer'=>'Fremd'])->assertNotFound();
 }
 public function test_unpublished_content_is_hidden_from_enrolled_participant():void
 {
  Storage::fake('local');$staff=User::factory()->create();$this->grant($staff);app(ModuleStateResolver::class)->set(SystemModule::where('key','participant_portal')->firstOrFail(),true,null,$staff->id);$location=Standort::factory()->create();$project=Projekt::factory()->create(['portal_feature_settings'=>['learning'=>true]]);$this->assign($project,$staff->person,$location);$staff->update(['current_team_id'=>$project->id]);$participant=Personen::factory()->create(['typ'=>'teilnehmer']);$participation=$this->assign($project,$participant,$location);$portal=User::factory()->create(['person_id'=>$participant->id]);$course=PortalCourse::query()->create(['project_id'=>$project->id,'created_by_user_id'=>$staff->id,'title'=>'Kurs','status'=>'published','self_enrollment'=>false]);PortalCourseEnrollment::query()->create(['course_id'=>$course->id,'project_person_id'=>$participation->id,'status'=>'enrolled','enrolled_at'=>now()]);$assignment=$course->assignments()->create(['title'=>'Entwurf','allow_text'=>true,'allow_file'=>false,'published'=>false,'sort_order'=>0]);$this->actingAs($portal)->postJson(route('participant-portal.learning.assignments.submit',$assignment),['text_answer'=>'Nicht erlaubt'])->assertNotFound();$this->assertDatabaseCount('portal_course_submissions',0);
 }
 private function assign(Projekt $p,Personen $person,Standort $s):ProjektHasPersonen{return ProjektHasPersonen::query()->create(['projekt_id'=>$p->id,'personen_id'=>$person->id,'standort_id'=>$s->id,'status'=>'aktiv']);}
 private function grant(User $u):void{$c=Berechtigungskategorie::query()->firstOrCreate(['name'=>'Lerninhalte'],['beschreibung'=>'']);Permission::query()->updateOrCreate(['name'=>'projekt.update','guard_name'=>'web'],['berechtigungskategorie_id'=>$c->id,'beschreibung'=>null]);app(PermissionRegistrar::class)->forgetCachedPermissions();$r=Role::query()->create(['name'=>'LearningContent-'.uniqid(),'guard_name'=>'web','color'=>'#123456']);RoleDataAccessSetting::query()->create(['role_id'=>$r->id,'team_scope'=>'own_projects','participant_scope'=>'all']);$u->assignRole($r);$u->givePermissionTo('projekt.update');}
}
