<?php

return [
    'legacy_generic' => [
        'Kaum erkennbar; umfassende Unterstützung ist erforderlich.',
        'Teilweise erkennbar; häufige Unterstützung ist erforderlich.',
        'Überwiegend angemessen; gelegentliche Unterstützung ist erforderlich.',
        'Sicher, selbstständig und wiederholt erkennbar.',
        'Besonders sicher, selbstständig und auch in anspruchsvollen Situationen erkennbar.',
    ],

    'competencies' => [
        'motivation' => [
            'Benötigt regelmäßig Aufforderung und Unterstützung, um sich mit einer Aufgabe zu beschäftigen und auf ein gutes Ergebnis hinzuarbeiten.',
            'Beginnt Aufgaben nach einem kurzen Impuls und bemüht sich zeitweise um ein gutes Ergebnis.',
            'Beschäftigt sich motiviert mit den gestellten Aufgaben und arbeitet auf ein gutes Ergebnis hin.',
            'Arbeitet selbstständig und motiviert, verfolgt gute Ergebnisse und entwickelt dabei eigene Ideen.',
            'Zeigt eine sehr hohe Eigeninitiative, bearbeitet auch schwierige Aufgaben engagiert und sucht selbstständig neue Herausforderungen.',
        ],
        'geduld' => [
            'Bricht längere oder schwierige Aufgaben häufig vorzeitig ab und benötigt Unterstützung, um ruhig weiterzuarbeiten.',
            'Arbeitet bei längeren Aufgaben zeitweise weiter, benötigt bei Verzögerungen oder Wiederholungen jedoch häufige Impulse.',
            'Bleibt bei längeren Aufgaben überwiegend ruhig und arbeitet auch bei Wartezeiten oder Wiederholungen weiter.',
            'Bearbeitet längere und schwierige Aufgaben geduldig und lässt sich durch Verzögerungen kaum aus der Ruhe bringen.',
            'Zeigt auch bei sehr langen, kleinschrittigen oder wiederholenden Aufgaben durchgehend große Geduld und Ruhe.',
        ],
        'ausdauer_persistenz' => [
            'Gibt bei Schwierigkeiten oder Misserfolgen schnell auf und benötigt umfassende Unterstützung zum Weiterarbeiten.',
            'Setzt die Arbeit nach Schwierigkeiten mit wiederholter Ermutigung fort und beendet Aufgaben nicht immer vollständig.',
            'Bleibt bei Schwierigkeiten an der Aufgabe und versucht mit gelegentlicher Unterstützung, das Ziel zu erreichen.',
            'Arbeitet auch bei Misserfolgen ausdauernd weiter, erprobt weitere Wege und bringt Aufgaben zuverlässig zu Ende.',
            'Verfolgt anspruchsvolle Ziele mit sehr hoher Ausdauer, verarbeitet Rückschläge konstruktiv und entwickelt selbstständig neue Lösungswege.',
        ],
        'kreativitaet' => [
            'Benötigt umfassende Anregung, um eigene Ideen oder Lösungsansätze zu entwickeln.',
            'Entwickelt mit Unterstützung einzelne Ideen und greift gelegentlich Anregungen anderer auf.',
            'Findet eigene Ideen und passende Lösungen und nutzt Anregungen anderer für die Aufgabe.',
            'Entwickelt zügig mehrere passende Ideen, prüft Anregungen und wählt eine geeignete Lösung aus.',
            'Entwickelt selbstständig vielfältige und originelle Lösungsansätze und passt diese flexibel an neue Anforderungen an.',
        ],
        'selbstreflexionsfaehigkeit' => [
            'Kann die eigene Arbeitsweise und das Ergebnis noch nicht realistisch einschätzen und benötigt dabei umfassende Unterstützung.',
            'Erkennt einzelne Stärken und Schwierigkeiten, braucht jedoch Hilfe, um die eigene Leistung angemessen einzuordnen.',
            'Schätzt die eigene Arbeitsweise und das Ergebnis überwiegend realistisch ein und kann einfache Verbesserungen benennen.',
            'Reflektiert das eigene Vorgehen selbstständig, erkennt Ursachen für Fehler und leitet passende Verbesserungen ab.',
            'Bewertet die eigene Leistung sehr differenziert, nutzt Rückmeldungen konstruktiv und überträgt Erkenntnisse selbstständig auf neue Aufgaben.',
        ],
        'gewissenhaftigkeit' => [
            'Benötigt umfassende Unterstützung, um sorgfältig zu arbeiten; Fehler und der Umgang mit Material werden nur wenig beachtet.',
            'Bemüht sich um sorgfältiges Arbeiten, kontrolliert Ergebnisse jedoch selten und benötigt wiederholt Hinweise.',
            'Arbeitet überwiegend sorgfältig, geht angemessen mit Material und Werkzeugen um und kontrolliert das Ergebnis meist.',
            'Arbeitet gewissenhaft und genau, kontrolliert Ergebnisse selbstständig, verbessert Fehler und beachtet Regeln zuverlässig.',
            'Arbeitet durchgehend besonders gewissenhaft und präzise, überprüft Ergebnisse anhand der Vorgaben und korrigiert Abweichungen selbstständig.',
        ],
        'grobmotorik' => [
            'Benötigt umfassende Unterstützung, um größere und kraftvolle Bewegungen zu koordinieren und Werkzeuge kontrolliert zu führen.',
            'Führt größere Bewegungsabläufe teilweise kontrolliert aus, benötigt bei Kraftdosierung und Werkzeugführung jedoch häufige Hinweise.',
            'Koordiniert größere Bewegungsabläufe überwiegend sicher und kann Kraft sowie Werkzeuge angemessen einsetzen.',
            'Führt kraftvolle und formgebende Bewegungen sicher, kontrolliert und mit angemessener Kraftdosierung aus.',
            'Steuert auch komplexe, kraftvolle Bewegungsabläufe sehr sicher, präzise und durchgehend kontrolliert.',
        ],
        'feinmotorik' => [
            'Benötigt umfassende Unterstützung, um kleine Gegenstände oder Werkzeuge gezielt und entlang von Vorgaben zu führen.',
            'Führt kleine Gegenstände und Werkzeuge teilweise sicher, arbeitet jedoch noch ungleichmäßig und mit mehreren Abweichungen.',
            'Setzt kleine Werkzeuge überwiegend sicher ein und arbeitet meist genau entlang vorgegebener Linien und Grenzen.',
            'Führt kleine Werkzeuge sicher und gefühlvoll und arbeitet mit nur wenigen Abweichungen präzise nach Vorgabe.',
            'Zeigt eine sehr sichere und präzise Handgeschicklichkeit und arbeitet auch bei hohen Genauigkeitsanforderungen nahezu fehlerfrei.',
        ],
        'raeumliches_vorstellungsvermoegen' => [
            'Benötigt umfassende Unterstützung beim Einschätzen von Abständen, Erkennen räumlicher Beziehungen und Arbeiten nach Vorlage.',
            'Erkennt räumliche Beziehungen teilweise und setzt Abstände, Spiegelungen oder Vorlagen mit wiederholter Unterstützung um.',
            'Schätzt Abstände überwiegend richtig ein, erkennt räumliche Beziehungen und arbeitet meist passend nach Vorlage.',
            'Erfasst räumliche Formen und Beziehungen sicher und setzt Abstände, Spiegelungen und Vorlagen genau um.',
            'Erkennt auch komplexe räumliche Zusammenhänge sehr schnell und setzt Formen, Abstände und Spiegelungen mit hoher Genauigkeit um.',
        ],
        'strukturierte_vorgehensweise' => [
            'Benötigt umfassende Unterstützung, um die Aufgabe zu gliedern, Hilfsmittel vorzubereiten und Arbeitsschritte sinnvoll zu ordnen.',
            'Ordnet einzelne Arbeitsschritte mit Unterstützung und kann benötigte Hilfsmittel teilweise passend vorbereiten und einsetzen.',
            'Gliedert Aufgaben in nachvollziehbare Schritte, bereitet Hilfsmittel vor und richtet den Arbeitsplatz zweckmäßig ein.',
            'Plant selbstständig sinnvolle Arbeitsschritte, setzt Hilfsmittel gezielt ein und nutzt vorhandenes Wissen sicher.',
            'Plant auch komplexe Aufgaben vorausschauend, passt Abläufe flexibel an und erweitert selbstständig das benötigte Wissen.',
        ],
        'analyse_problemloesefaehigkeit' => [
            'Benötigt umfassende Unterstützung, um Schwierigkeiten und logische Zusammenhänge zu erkennen und einen Lösungsweg zu finden.',
            'Erkennt naheliegende Probleme teilweise und entwickelt mit Unterstützung einen grundsätzlich passenden Lösungsweg.',
            'Erkennt Probleme und logische Zusammenhänge, entwickelt passende Lösungen und setzt diese überwiegend zielgerichtet um.',
            'Analysiert Problemstellungen sicher, entwickelt mehrere Lösungswege und setzt eine geeignete Lösung strukturiert um.',
            'Analysiert auch komplexe Probleme sehr sicher, überprüft Lösungswege kritisch und passt das Vorgehen flexibel und selbstständig an.',
        ],
        'aufgabenverstaendnis' => [
            'Benötigt umfassende Unterstützung, um Aufgabenstellungen und Arbeitsanweisungen zu verstehen und umzusetzen.',
            'Versteht einfache Aufgaben überwiegend, setzt Arbeitsanweisungen jedoch nur teilweise oder nach wiederholter Erklärung um.',
            'Versteht Aufgabenstellungen und Arbeitsanweisungen und setzt die wesentlichen Anforderungen angemessen um.',
            'Erfasst Aufgaben und Arbeitsanweisungen schnell und richtig und setzt alle Anforderungen sicher um.',
            'Versteht auch komplexe und mehrschrittige Aufgaben sehr schnell, verarbeitet relevante Informationen sicher und setzt Anforderungen vollständig um.',
        ],
        'teamfaehigkeit' => [
            'Benötigt umfassende Unterstützung, um sich abzustimmen und konstruktiv mit anderen an einer gemeinsamen Aufgabe zu arbeiten.',
            'Beteiligt sich zeitweise an der Gruppenarbeit, benötigt jedoch häufige Impulse zur Abstimmung und gemeinsamen Lösungsfindung.',
            'Stimmt sich mit anderen ab, arbeitet konstruktiv in der Gruppe und beteiligt sich angemessen an der gemeinsamen Lösung.',
            'Arbeitet sehr kooperativ, bringt eigene Ideen ein, berücksichtigt andere und unterstützt die Gruppe aktiv beim Erreichen des Ziels.',
            'Fördert die Zusammenarbeit in besonderem Maß, verbindet unterschiedliche Ideen, übernimmt Verantwortung und stärkt die gemeinsame Lösungsfindung.',
        ],
        'kommunikationsfaehigkeit' => [
            'Benötigt umfassende Unterstützung, um Kontakt aufzunehmen, sich verständlich auszudrücken und auf Beiträge anderer passend zu reagieren.',
            'Nimmt teilweise Kontakt auf und äußert eigene Gedanken, benötigt jedoch häufige Unterstützung beim Zuhören und verständlichen Reagieren.',
            'Drückt sich verständlich aus, hört anderen zu und reagiert überwiegend passend auf deren Beiträge.',
            'Kommuniziert klar und situationsangemessen, hört aktiv zu, fragt bei Unklarheiten nach und berücksichtigt verbale sowie nonverbale Signale.',
            'Kommuniziert sehr sicher und differenziert, vertritt Standpunkte sachlich, moderiert den Austausch und bezieht andere gezielt ein.',
        ],
        'aufmerksamkeit_achtsamkeit' => [
            'Benötigt umfassende Unterstützung, um die Arbeitssituation, andere Personen sowie Materialien aufmerksam und respektvoll wahrzunehmen.',
            'Nimmt wichtige Hinweise und Bedürfnisse teilweise wahr, benötigt jedoch wiederholt Erinnerung an einen aufmerksamen und respektvollen Umgang.',
            'Arbeitet aufmerksam, verhält sich respektvoll und berücksichtigt die Situation, andere Personen und Materialien angemessen.',
            'Handelt durchgehend aufmerksam und rücksichtsvoll, erkennt relevante Veränderungen frühzeitig und reagiert passend.',
            'Zeigt eine besonders ausgeprägte Achtsamkeit, erfasst auch feine soziale und situative Signale und handelt vorausschauend und verantwortungsvoll.',
        ],
        'sprachkompetenz' => [
            'Benötigt umfassende Unterstützung, um gesprochene Informationen zu verstehen und eigene Inhalte verständlich wiederzugeben.',
            'Versteht einfache mündliche Informationen überwiegend und gibt Inhalte mit Unterstützung verständlich weiter.',
            'Versteht gesprochene Informationen und gibt wesentliche Inhalte richtig und verständlich wieder.',
            'Erfasst auch umfangreichere mündliche Informationen sicher und formuliert eigene Gedanken klar und adressatengerecht.',
            'Versteht komplexe sprachliche Inhalte sehr sicher und stellt Informationen präzise, strukturiert und situationsangemessen dar.',
        ],
    ],
];
