<?php

return [
    'themen' => [
        'erste_hilfe' => 'Erste Hilfe',
        'brandschutz' => 'Brandschutz',
        'ladungssicherung' => 'Ladungssicherung',
        'autogen_schweissen_schneiden' => 'Autogen Schweißen/Schneiden',
        'mig_mag_schweissen' => 'MIG/MAG Schweißen',
        'wig_schweissen' => 'WIG Schweißen',
        'elektrische_geraete' => 'Elektrische Geräte',
        'elektroschweissen' => 'Elektroschweißen',
        'drehmaschine' => 'Drehmaschine',
        'fraesmaschine' => 'Fräsmaschine',
        'handhebelschere' => 'Handhebelschere',
        'kalt_kreis_kappsaege' => 'Kalt Kreis-, Kappsäge',
        'band_buegelsaege' => 'Band-, Bügelsäge',
        'saeulenbohrmaschine' => 'Säulenbohrmaschine',
        'stossmaschine' => 'Stoßmaschine',
        'arbeitsbuehne_fahrbar' => 'Arbeitsbühne fahrbar',
        'schleifbock' => 'Schleifbock',
        'punktschweissmaschine' => 'Punktschweißmaschine',
        'schmieden' => 'Schmieden',
        'schlagschere' => 'Schlagschere',
        'leitern_und_tritte' => 'Leitern und Tritte',
        'pers_schutzausruestung' => 'Pers. Schutzausrüstung',
        'umgang_gefahrstoffe' => 'Umgang mit Gefahrstoffen',
        'loeten_allgemein' => 'Löten allgemein',
        'hautschutz' => 'Hautschutz',
        'heben_und_tragen' => 'Heben und Tragen',
        'arbeitsunfall' => 'Arbeitsunfall',
        'metallwerkstatt_allgemein' => 'Metallwerkstatt allgemein',
        'druckluft' => 'Druckluft',
    ],
];
