<?php
namespace App\Http\Controllers;
use App\Models\ParticipantCvEntry;use App\Models\ParticipantCvVersion;use App\Models\ParticipantPortalProfile;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Validation\Rule;use Inertia\Inertia;
class ParticipantCvController extends Controller
{
 public function index(Request $request){return Inertia::render('ParticipantPortal/Resume',['participant'=>$request->user()->person->only(['id','vorname','nachname','geburtsdatum']),'profile'=>ParticipantPortalProfile::query()->where('person_id',$request->user()->person_id)->first(),'entries'=>ParticipantCvEntry::query()->where('person_id',$request->user()->person_id)->orderBy('type')->orderBy('sort_order')->get(),'versions'=>ParticipantCvVersion::query()->where('person_id',$request->user()->person_id)->latest('version')->get()]);}
 public function store(Request $request){$entry=ParticipantCvEntry::query()->create([...$request->validate($this->rules()),'person_id'=>$request->user()->person_id]);return response()->json(['message'=>'Lebenslaufeintrag wurde angelegt.','entry'=>$entry],201);}
 public function update(Request $request,ParticipantCvEntry $entry){$this->own($request,$entry->person_id);$entry->update($request->validate($this->rules()));return response()->json(['message'=>'Lebenslaufeintrag wurde gespeichert.','entry'=>$entry->fresh()]);}
 public function destroy(Request $request,ParticipantCvEntry $entry){$this->own($request,$entry->person_id);$entry->delete();return response()->json(['message'=>'Lebenslaufeintrag wurde gelöscht.']);}
 public function createVersion(Request $request){$data=$request->validate(['label'=>['nullable','string','max:255']]);$person=$request->user()->person;$snapshot=$this->snapshot($person->id);$canonical=json_encode($snapshot,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRESERVE_ZERO_FRACTION);$version=DB::transaction(function()use($request,$person,$data,$snapshot,$canonical){$next=(int)ParticipantCvVersion::query()->where('person_id',$person->id)->lockForUpdate()->max('version')+1;return ParticipantCvVersion::query()->create(['person_id'=>$person->id,'version'=>$next,'label'=>$data['label']??null,'snapshot'=>$snapshot,'snapshot_sha256'=>hash('sha256',$canonical),'created_by_user_id'=>$request->user()->id,'created_at'=>now()]);});return response()->json(['message'=>'Unveränderliche Lebenslaufversion wurde erstellt.','version'=>$version],201);}
 public function download(Request $request,ParticipantCvVersion $version){$this->own($request,$version->person_id);$name='lebenslauf-v'.$version->version.'-'.now()->format('Y-m-d').'.json';return response()->streamDownload(fn()=>print(json_encode(['version'=>$version->version,'label'=>$version->label,'created_at'=>$version->created_at,'sha256'=>$version->snapshot_sha256,'resume'=>$version->snapshot],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)),$name,['Content-Type'=>'application/json; charset=UTF-8','Cache-Control'=>'no-store, private']);}
 public function print(Request $request,ParticipantCvVersion $version){$this->own($request,$version->person_id);return Inertia::render('ParticipantPortal/ResumePrint',['version'=>$version]);}
 private function snapshot(int $personId):array{$person=\App\Models\Personen::query()->findOrFail($personId);$profile=ParticipantPortalProfile::query()->where('person_id',$personId)->first();return['person'=>$person->only(['vorname','nachname','geburtsdatum']),'profile'=>$profile?->only(['professional_headline','career_goal','skills','interests','available_from']),'entries'=>ParticipantCvEntry::query()->where('person_id',$personId)->orderBy('type')->orderBy('sort_order')->get()->toArray()];}
 private function own(Request $request,int $personId):void{abort_unless((int)$personId===(int)$request->user()->person_id,404);}
 private function rules():array{return['type'=>['required',Rule::in(['experience','education','qualification','language','skill'])],'title'=>['required','string','max:255'],'organization'=>['nullable','string','max:255'],'location'=>['nullable','string','max:255'],'starts_at'=>['nullable','date'],'ends_at'=>['nullable','date','after_or_equal:starts_at'],'current'=>['required','boolean'],'description'=>['nullable','string','max:5000'],'proficiency'=>['nullable','string','max:100'],'sort_order'=>['required','integer','min:0','max:9999']];}
}
