<?php
namespace App\Http\Controllers;
use App\Models\ParticipantCareerDocument;use App\Models\ParticipantPortalProfile;use App\Models\Personen;use App\Services\CvTemplateCatalog;use Barryvdh\DomPDF\Facade\Pdf;use Illuminate\Http\Request;use Illuminate\Validation\Rule;use Inertia\Inertia;
class ParticipantCareerStudioController extends Controller {
 public function __construct(private readonly CvTemplateCatalog $templates){}
 public function index(Request $r){$person=$r->user()->person;return Inertia::render('ParticipantPortal/CareerStudio',['participant'=>$person->only(['id','vorname','nachname','geburtsdatum']),'documents'=>ParticipantCareerDocument::where('person_id',$person->id)->latest('updated_at')->get(),'templates'=>$this->templates->all(),'starter'=>$this->starter($person)]);}
 public function store(Request $r){$data=$r->validate($this->rules());$doc=ParticipantCareerDocument::create([...$data,'person_id'=>$r->user()->person_id,'created_by_user_id'=>$r->user()->id]);return response()->json(['message'=>'Dokument wurde erstellt.','document'=>$doc],201);}
 public function update(Request $r,ParticipantCareerDocument $document){$this->own($r,$document);$document->update($r->validate($this->rules()));return response()->json(['message'=>'Dokument wurde gespeichert.','document'=>$document->fresh()]);}
 public function duplicate(Request $r,ParticipantCareerDocument $document){$this->own($r,$document);$copy=$document->replicate();$copy->title=$document->title.' – Kopie';$copy->created_by_user_id=$r->user()->id;$copy->save();return response()->json(['message'=>'Kopie wurde erstellt.','document'=>$copy],201);}
 public function destroy(Request $r,ParticipantCareerDocument $document){$this->own($r,$document);abort_if($document->applications()->exists(),422,'Das Dokument ist mit einer Bewerbung verknüpft.');$document->delete();return response()->json(['message'=>'Dokument wurde gelöscht.']);}
 public function preview(Request $r,ParticipantCareerDocument $document){$this->own($r,$document);return $this->pdf($document)->stream($this->filename($document));}
 public function download(Request $r,ParticipantCareerDocument $document){$this->own($r,$document);return $this->pdf($document)->download($this->filename($document));}
 public function pdf(ParticipantCareerDocument $document){return Pdf::loadView('pdf.career-document',['document'=>$document,'template'=>$this->templates->find($document->template_key)])->setPaper('a4');}
 private function filename($d){return str($d->title)->slug().'.pdf';}
 private function own(Request $r,$d){abort_unless((int)$d->person_id===(int)$r->user()->person_id,404);}
 private function rules(){return['type'=>['required',Rule::in(['resume','cover_page','cover_letter'])],'title'=>['required','string','max:255'],'template_key'=>['required',Rule::in($this->templates->keys())],'content'=>['required','array'],'content.full_name'=>['nullable','string','max:255'],'content.headline'=>['nullable','string','max:255'],'content.recipient'=>['nullable','string','max:1000'],'content.subject'=>['nullable','string','max:255'],'content.body'=>['nullable','string','max:15000'],'content.summary'=>['nullable','string','max:5000'],'content.contact'=>['nullable','string','max:1000'],'content.entries'=>['nullable','array','max:100'],'content.entries.*.section'=>['nullable','string','max:100'],'content.entries.*.title'=>['nullable','string','max:255'],'content.entries.*.subtitle'=>['nullable','string','max:255'],'content.entries.*.period'=>['nullable','string','max:100'],'content.entries.*.description'=>['nullable','string','max:5000'],'is_default'=>['sometimes','boolean']];}
 private function starter(Personen $p){$profile=ParticipantPortalProfile::where('person_id',$p->id)->first();return['full_name'=>trim($p->vorname.' '.$p->nachname),'headline'=>$profile?->professional_headline,'summary'=>$profile?->career_goal,'contact'=>'','recipient'=>'','subject'=>'Bewerbung als …','body'=>"Sehr geehrte Damen und Herren,\n\nmit großem Interesse bewerbe ich mich bei Ihnen.\n\nMit freundlichen Grüßen\n".trim($p->vorname.' '.$p->nachname),'entries'=>[]];}
}
