<?php
namespace App\Http\Controllers;
use App\Models\ParticipantDataRequest;use App\Models\Personen;use App\Models\ProjektHasPersonen;use App\Services\Participants\ParticipantDataExportService;use App\Services\Projects\ActiveProjectContext;use Illuminate\Http\Request;use Illuminate\Validation\Rule;use Inertia\Inertia;
class ParticipantDataRequestController extends Controller
{
 public function __construct(private readonly ActiveProjectContext $activeProjectContext,private readonly ParticipantDataExportService $exports){}
 public function portalIndex(Request $request){$participations=ProjektHasPersonen::query()->where('personen_id',$request->user()->person_id)->with('projekt:id,name')->get();return Inertia::render('ParticipantPortal/DataRequests',['participations'=>$participations,'requests'=>ParticipantDataRequest::query()->where('person_id',$request->user()->person_id)->with(['participation.projekt:id,name','resolver:id,username'])->latest()->get()]);}
 public function portalStore(Request $request){$data=$request->validate(['project_person_id'=>['required','integer'],'type'=>['required',Rule::in(['access_export','correction','deletion'])],'request_details'=>['nullable','string','max:5000']]);$participation=ProjektHasPersonen::query()->whereKey($data['project_person_id'])->where('personen_id',$request->user()->person_id)->firstOrFail();abort_if(ParticipantDataRequest::query()->where('person_id',$request->user()->person_id)->where('type',$data['type'])->where('status','submitted')->exists(),422,'Für diesen Antrag besteht bereits eine offene Anfrage.');$item=ParticipantDataRequest::query()->create([...$data,'person_id'=>$request->user()->person_id,'requested_by_user_id'=>$request->user()->id,'status'=>'submitted']);return response()->json(['message'=>'Anfrage wurde eingereicht.','request'=>$item->load('participation.projekt:id,name')],201);}
 public function resolve(Request $request,ParticipantDataRequest $dataRequest){$this->authorizeStaff($request,$dataRequest);$data=$request->validate(['status'=>['required',Rule::in(['approved','rejected','completed'])],'resolution_note'=>['required','string','max:5000'],'identity_verification_method'=>['required','string','max:255']]);abort_if($dataRequest->status!=='submitted'&&$data['status']!=='completed',422,'Diese Anfrage wurde bereits bearbeitet.');abort_if($data['status']==='completed'&&$dataRequest->status!=='approved',422,'Nur freigegebene Anfragen können abgeschlossen werden.');$dataRequest->update([...$data,'resolved_by_user_id'=>$request->user()->id,'identity_verified_at'=>now(),'resolved_at'=>now(),'completed_at'=>$data['status']==='completed'?now():null]);return response()->json(['message'=>'Anfrage wurde bearbeitet.','request'=>$dataRequest->fresh()->load('resolver:id,username')]);}
 public function download(Request $request,ParticipantDataRequest $dataRequest){abort_unless((int)$dataRequest->person_id===(int)$request->user()->person_id,404);abort_unless($dataRequest->type==='access_export'&&in_array($dataRequest->status,['approved','completed'],true)&&$dataRequest->identity_verified_at,403);$payload=$this->exports->build($request->user()->person);$dataRequest->update(['last_downloaded_at'=>now(),'completed_at'=>$dataRequest->completed_at??now(),'status'=>'completed']);$name='matrix-datenauskunft-'.now()->format('Y-m-d-His').'.json';return response()->streamDownload(fn()=>print(json_encode($payload,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)),$name,['Content-Type'=>'application/json; charset=UTF-8','Cache-Control'=>'no-store, private']);}
 private function authorizeStaff(Request $request,ParticipantDataRequest $item):void{$project=$this->activeProjectContext->currentAvailableFor($request->user());$item->load('participation');abort_unless($project&&(int)$item->participation->projekt_id===(int)$project->id,404);abort_unless(Personen::query()->teilnehmer()->visibleForUser($request->user())->whereKey($item->person_id)->exists(),403);}
}
