<?php
namespace App\Http\Controllers;
use App\Models\ParticipantApplication;use App\Models\ParticipantApplicationStatusHistory;use App\Models\ParticipantJobRecommendation;use App\Models\Personen;use App\Models\ProjektHasPersonen;use App\Services\Projects\ActiveProjectContext;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class ParticipantJobRecommendationController extends Controller
{
 public function __construct(private readonly ActiveProjectContext $activeProjectContext){}
 public function staffStore(Request $request,ProjektHasPersonen $participation){$this->staffParticipation($request,$participation);$data=$request->validate($this->rules());$item=ParticipantJobRecommendation::query()->create([...$data,'project_person_id'=>$participation->id,'recommended_by_user_id'=>$request->user()->id,'recommended_at'=>now()]);return response()->json(['message'=>'Stelle wurde empfohlen.','recommendation'=>$item->load('recommender:id,username,person_id')],201);}
 public function dismiss(Request $request,ParticipantJobRecommendation $recommendation){$this->portalRecommendation($request,$recommendation);abort_if($recommendation->converted_application_id,422,'Diese Empfehlung wurde bereits als Bewerbung übernommen.');$recommendation->update(['viewed_at'=>$recommendation->viewed_at??now(),'dismissed_at'=>now()]);return response()->json(['message'=>'Empfehlung wurde ausgeblendet.']);}
 public function viewed(Request $request,ParticipantJobRecommendation $recommendation){$this->portalRecommendation($request,$recommendation);if(!$recommendation->viewed_at)$recommendation->update(['viewed_at'=>now()]);return response()->json(['message'=>'Empfehlung wurde als angesehen markiert.']);}
 public function convert(Request $request,ParticipantJobRecommendation $recommendation){$participation=$this->portalRecommendation($request,$recommendation);abort_unless($participation->projekt->portalFeatureEnabled('application_management'),404);abort_if($recommendation->converted_application_id,422,'Diese Empfehlung wurde bereits übernommen.');$application=DB::transaction(function()use($request,$recommendation,$participation){$locked=ParticipantJobRecommendation::query()->lockForUpdate()->findOrFail($recommendation->id);abort_if($locked->converted_application_id,422,'Diese Empfehlung wurde bereits übernommen.');if($locked->external_ref)abort_if(ParticipantApplication::query()->where('project_person_id',$participation->id)->where('external_ref',$locked->external_ref)->exists(),422,'Für diese Stelle besteht bereits eine Bewerbung.');$app=ParticipantApplication::query()->create(['project_person_id'=>$participation->id,'created_by_user_id'=>$request->user()->id,'external_ref'=>$locked->external_ref,'title'=>$locked->title,'employer'=>$locked->employer,'location'=>$locked->location,'source_url'=>$locked->source_url,'status'=>'draft','notes'=>$locked->note]);ParticipantApplicationStatusHistory::query()->create(['application_id'=>$app->id,'from_status'=>null,'to_status'=>'draft','changed_by_user_id'=>$request->user()->id,'changed_at'=>now()]);$locked->update(['converted_application_id'=>$app->id,'viewed_at'=>$locked->viewed_at??now()]);return $app;});return response()->json(['message'=>'Empfehlung wurde als Bewerbung übernommen.','application'=>$application->load('participation.projekt:id,name'),'recommendation'=>$recommendation->fresh()],201);}
 private function staffParticipation(Request $request,ProjektHasPersonen $p):void{$project=$this->activeProjectContext->currentAvailableFor($request->user());abort_unless($project&&(int)$p->projekt_id===(int)$project->id,404);abort_unless($project->portalFeatureEnabled('job_search')||$project->portalFeatureEnabled('application_management'),404);abort_unless(Personen::query()->teilnehmer()->visibleForUser($request->user())->whereKey($p->personen_id)->exists(),403);}
 private function portalRecommendation(Request $request,ParticipantJobRecommendation $item):ProjektHasPersonen{$p=ProjektHasPersonen::query()->whereKey($item->project_person_id)->where('personen_id',$request->user()->person_id)->with('projekt')->firstOrFail();abort_unless($p->projekt->portalFeatureEnabled('job_search')||$p->projekt->portalFeatureEnabled('application_management'),404);return $p;}
 private function rules():array{return['external_ref'=>['nullable','string','max:150'],'title'=>['required','string','max:255'],'employer'=>['nullable','string','max:255'],'location'=>['nullable','string','max:255'],'source_url'=>['nullable','url','max:2048'],'note'=>['nullable','string','max:3000']];}
}
