<?php
namespace App\Http\Controllers;
use App\Models\ParticipantApplication;use App\Models\ParticipantPortalDocument;use App\Models\Personen;use App\Models\ProjektHasPersonen;use App\Services\Projects\ActiveProjectContext;use Illuminate\Http\Request;
class ParticipantApplicationPackageController extends Controller
{
 public function __construct(private readonly ActiveProjectContext $activeProjectContext){}
 public function portalSync(Request $request,ParticipantApplication $application){$participation=$this->portalApplication($request,$application);$ids=$request->validate(['document_ids'=>['present','array'],'document_ids.*'=>['integer']])['document_ids'];$documents=$this->validDocuments($participation,$ids,true);abort_unless($documents->count()===count(array_unique($ids)),422,'Alle Dokumente müssen freigegeben sein und zur Projektteilnahme gehören.');$application->documents()->syncWithPivotValues($documents->pluck('id'),['added_by_user_id'=>$request->user()->id]);$this->resetApproval($application);return response()->json(['message'=>'Bewerbungspaket wurde aktualisiert.','application'=>$this->load($application)]);}
 public function staffSync(Request $request,ParticipantApplication $application){$participation=$this->staffApplication($request,$application);$ids=$request->validate(['document_ids'=>['present','array'],'document_ids.*'=>['integer']])['document_ids'];$documents=$this->validDocuments($participation,$ids,false);abort_unless($documents->count()===count(array_unique($ids)),422,'Alle Dokumente müssen geprüft sein und zur Projektteilnahme gehören.');$application->documents()->syncWithPivotValues($documents->pluck('id'),['added_by_user_id'=>$request->user()->id]);$this->resetApproval($application);return response()->json(['message'=>'Bewerbungspaket wurde aktualisiert.','application'=>$this->load($application)]);}
 public function portalApprove(Request $request,ParticipantApplication $application){$this->portalApplication($request,$application);abort_if($application->documents()->count()===0,422,'Wählen Sie zuerst mindestens ein Dokument.');$application->update(['participant_package_approved_at'=>now()]);return response()->json(['message'=>'Bewerbungspaket wurde von Ihnen freigegeben.','application'=>$this->load($application)]);}
 public function staffApprove(Request $request,ParticipantApplication $application){$this->staffApplication($request,$application);abort_if($application->documents()->count()===0,422,'Wählen Sie zuerst mindestens ein Dokument.');$application->update(['staff_package_approved_at'=>now(),'staff_package_approved_by_user_id'=>$request->user()->id]);return response()->json(['message'=>'Bewerbungspaket wurde fachlich geprüft.','application'=>$this->load($application)]);}
 private function portalApplication(Request $request,ParticipantApplication $app):ProjektHasPersonen{$p=ProjektHasPersonen::query()->whereKey($app->project_person_id)->where('personen_id',$request->user()->person_id)->with('projekt')->firstOrFail();abort_unless($p->projekt->portalFeatureEnabled('application_management'),404);return $p;}
 private function staffApplication(Request $request,ParticipantApplication $app):ProjektHasPersonen{$app->load('participation');$p=$app->participation;$project=$this->activeProjectContext->currentAvailableFor($request->user());abort_unless($project&&(int)$p->projekt_id===(int)$project->id&&$project->portalFeatureEnabled('application_management'),404);abort_unless(Personen::query()->teilnehmer()->visibleForUser($request->user())->whereKey($p->personen_id)->exists(),403);return $p;}
 private function validDocuments(ProjektHasPersonen $p,array $ids,bool $participant){return ParticipantPortalDocument::query()->where('project_person_id',$p->id)->whereIn('id',$ids)->where('status','approved')->when($participant,fn($q)=>$q->where('visible_to_participant',true))->get();}
 private function resetApproval(ParticipantApplication $app):void{$app->update(['participant_package_approved_at'=>null,'staff_package_approved_at'=>null,'staff_package_approved_by_user_id'=>null]);}
 private function load(ParticipantApplication $app):ParticipantApplication{return $app->fresh()->load(['participation.projekt:id,name','statusHistory','documents']);}
}
