<?php
namespace App\Http\Controllers;
use App\Mail\ParticipantApplicationSubmitted;use App\Models\ParticipantApplication;use App\Models\ParticipantApplicationActivity;use App\Models\ParticipantApplicationStatusHistory;use App\Models\ParticipantCareerDocument;use App\Models\ProjektHasPersonen;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Mail;
class ParticipantApplicationDispatchController extends Controller {
 public function __construct(private readonly ParticipantCareerStudioController $studio){}
 public function sync(Request $r,ParticipantApplication $application){$this->own($r,$application);$ids=$r->validate(['document_ids'=>['present','array','max:10'],'document_ids.*'=>['integer']])['document_ids'];$docs=ParticipantCareerDocument::where('person_id',$r->user()->person_id)->whereIn('id',$ids)->get();abort_unless($docs->count()===count(array_unique($ids)),422,'Ungültige Dokumentauswahl.');$application->careerDocuments()->sync(collect($ids)->mapWithKeys(fn($id,$i)=>[$id=>['sort_order'=>$i]])->all());$this->activity($application,$r,'document_linked','Bewerbungsunterlagen aktualisiert.',['document_ids'=>$ids]);return response()->json(['message'=>'Unterlagen wurden verknüpft.','application'=>$this->load($application)]);}
 public function note(Request $r,ParticipantApplication $application){$this->own($r,$application);$body=$r->validate(['body'=>['required','string','max:5000']])['body'];$activity=$this->activity($application,$r,'note',$body);return response()->json(['message'=>'Notiz gespeichert.','activity'=>$activity],201);}
 public function send(Request $r,ParticipantApplication $application){$this->own($r,$application);$data=$r->validate(['to'=>['required','email:rfc','max:255'],'subject'=>['required','string','max:255'],'message'=>['required','string','max:10000']]);$application->load('careerDocuments');abort_if($application->careerDocuments->isEmpty(),422,'Bitte verknüpfen Sie zuerst mindestens ein Bewerbungsdokument.');
  $attachments=[];foreach($application->careerDocuments as $doc){$attachments[]=['data'=>$this->studio->pdf($doc)->output(),'name'=>str($doc->title)->slug().'.pdf'];}
  Mail::to($data['to'])->send(new ParticipantApplicationSubmitted($data['subject'],$data['message'],$attachments));
  DB::transaction(function()use($application,$r,$data,$attachments){$old=$application->status;$application->update(['recipient_email'=>$data['to'],'email_subject'=>$data['subject'],'status'=>'sent','applied_at'=>$application->applied_at??today(),'last_sent_at'=>now()]);if($old!=='sent')ParticipantApplicationStatusHistory::create(['application_id'=>$application->id,'from_status'=>$old,'to_status'=>'sent','changed_by_user_id'=>$r->user()->id,'changed_at'=>now()]);$this->activity($application,$r,'email_sent','Bewerbung per E-Mail versendet.',['to'=>$data['to'],'subject'=>$data['subject'],'attachments'=>collect($attachments)->pluck('name')]);});return response()->json(['message'=>'Bewerbung wurde per E-Mail versendet.','application'=>$this->load($application)]);}
 private function own(Request $r,$a){ProjektHasPersonen::whereKey($a->project_person_id)->where('personen_id',$r->user()->person_id)->firstOrFail();}
 private function activity($a,$r,$type,$body,$meta=null){return ParticipantApplicationActivity::create(['application_id'=>$a->id,'user_id'=>$r->user()->id,'type'=>$type,'body'=>$body,'metadata'=>$meta,'occurred_at'=>now()]);}
 private function load($a){return $a->fresh()->load(['participation.projekt:id,name','statusHistory','documents','careerDocuments','activities']);}
}
