<?php
namespace App\Http\Controllers;
use App\Models\ParticipantPortalDocument;use App\Models\Personen;use App\Models\ProjektHasPersonen;use App\Services\Projects\ActiveProjectContext;use Illuminate\Http\Request;use Illuminate\Support\Facades\Storage;use Illuminate\Validation\Rule;
class ParticipantDocumentController extends Controller
{
 public function __construct(private readonly ActiveProjectContext $activeProjectContext){}
 public function store(Request $request,ProjektHasPersonen $participation){$project=$this->authorizeParticipation($request,$participation);$data=$request->validate(['category'=>['required','string','max:80'],'visible_to_participant'=>['required','boolean'],'file'=>['required','file','max:10240','mimes:pdf,doc,docx,jpg,jpeg,png']]);$file=$data['file'];$path=$file->store('participant-portal/'.$participation->personen_id,'local');$document=ParticipantPortalDocument::query()->create(['project_person_id'=>$participation->id,'uploaded_by_user_id'=>$request->user()->id,'original_name'=>$file->getClientOriginalName(),'path'=>$path,'mime_type'=>$file->getMimeType()?:'application/octet-stream','size'=>$file->getSize(),'category'=>$data['category'],'status'=>'approved','visible_to_participant'=>(bool)$data['visible_to_participant'],'reviewed_by_user_id'=>$request->user()->id,'reviewed_at'=>now()]);return response()->json(['message'=>'Dokument wurde gespeichert.','document'=>$document->load(['uploader:id,username','reviewer:id,username'])],201);}
 public function review(Request $request,ParticipantPortalDocument $document){$document->load('participation');$this->authorizeParticipation($request,$document->participation);$data=$request->validate(['status'=>['required',Rule::in(['approved','rejected'])],'review_note'=>['nullable','string','max:2000'],'visible_to_participant'=>['required','boolean']]);$document->update([...$data,'reviewed_by_user_id'=>$request->user()->id,'reviewed_at'=>now()]);return response()->json(['message'=>'Dokument wurde geprüft.','document'=>$document->fresh()->load(['uploader:id,username','reviewer:id,username'])]);}
 public function download(Request $request,ParticipantPortalDocument $document){$document->load('participation');$this->authorizeParticipation($request,$document->participation);abort_unless(Storage::disk('local')->exists($document->path),404);return Storage::disk('local')->download($document->path,$document->original_name,['Content-Type'=>$document->mime_type]);}
 private function authorizeParticipation(Request $request,ProjektHasPersonen $p){$project=$this->activeProjectContext->currentAvailableFor($request->user());abort_unless($project&&(int)$p->projekt_id===(int)$project->id,404);abort_unless(Personen::query()->teilnehmer()->visibleForUser($request->user())->whereKey($p->personen_id)->exists(),403);return $project;}
}
