<?php
namespace App\Http\Controllers;
use App\Models\ParticipantPortalDocument;use App\Models\ProjektHasPersonen;use Illuminate\Http\Request;use Illuminate\Support\Facades\Storage;use Inertia\Inertia;
class PortalDocumentController extends Controller
{
 public function index(Request $request){$participations=ProjektHasPersonen::query()->where('personen_id',$request->user()->person_id)->with('projekt')->get()->filter(fn($p)=>$p->projekt->portalFeatureEnabled('profile'))->values();return Inertia::render('ParticipantPortal/Documents',['participations'=>$participations,'documents'=>ParticipantPortalDocument::query()->whereIn('project_person_id',$participations->pluck('id'))->where('visible_to_participant',true)->with('participation.projekt:id,name')->latest()->get(),'categories'=>$this->categories()]);}
 public function store(Request $request){$data=$request->validate(['project_person_id'=>['required','integer'],'category'=>['required','string','max:80'],'file'=>['required','file','max:10240','mimes:pdf,doc,docx,jpg,jpeg,png']]);$participation=$this->participation($request,(int)$data['project_person_id']);$file=$data['file'];$path=$file->store('participant-portal/'.$request->user()->person_id,'local');$document=ParticipantPortalDocument::query()->create(['project_person_id'=>$participation->id,'uploaded_by_user_id'=>$request->user()->id,'original_name'=>$file->getClientOriginalName(),'path'=>$path,'mime_type'=>$file->getMimeType()?:'application/octet-stream','size'=>$file->getSize(),'category'=>$data['category'],'status'=>'pending','visible_to_participant'=>true]);return response()->json(['message'=>'Dokument wurde hochgeladen und wartet auf Prüfung.','document'=>$document->load('participation.projekt:id,name')],201);}
 public function download(Request $request,ParticipantPortalDocument $document){$participation=$this->participation($request,$document->project_person_id);abort_unless((int)$document->project_person_id===(int)$participation->id&&$document->visible_to_participant,404);abort_unless(Storage::disk('local')->exists($document->path),404);return Storage::disk('local')->download($document->path,$document->original_name,['Content-Type'=>$document->mime_type]);}
 public function destroy(Request $request,ParticipantPortalDocument $document){$this->participation($request,$document->project_person_id);abort_unless((int)$document->uploaded_by_user_id===(int)$request->user()->id&&$document->status==='pending',403);Storage::disk('local')->delete($document->path);$document->delete();return response()->json(['message'=>'Dokument wurde gelöscht.']);}
 private function participation(Request $request,int $id):ProjektHasPersonen{$p=ProjektHasPersonen::query()->whereKey($id)->where('personen_id',$request->user()->person_id)->with('projekt')->firstOrFail();abort_unless($p->projekt->portalFeatureEnabled('profile'),404);return $p;}
 private function categories():array{return ['cv'=>'Lebenslauf','application'=>'Bewerbungsunterlage','certificate'=>'Zeugnis/Nachweis','other'=>'Sonstiges'];}
}
