<?php
namespace App\Http\Controllers;
use App\Models\ProjectConsentDefinition;use App\Models\Projekt;use App\Services\Projects\ActiveProjectContext;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Validation\Rule;use Inertia\Inertia;
class ProjectConsentController extends Controller
{
 public function __construct(private readonly ActiveProjectContext $activeProjectContext){}
 public function index(Request $request,Projekt $projekt){$this->authorizeProject($request,$projekt);$versions=ProjectConsentDefinition::query()->where('project_id',$projekt->id)->orderBy('key')->orderByDesc('version')->get();return Inertia::render('Projekt/Consents',['projekt'=>$projekt->only(['id','name']),'definitions'=>$versions->groupBy('key')->map(fn($items)=>['current'=>$items->first(),'versions'=>$items->values()])->values()]);}
 public function store(Request $request,Projekt $projekt){$this->authorizeProject($request,$projekt);$data=$request->validate($this->rules(true));$key=strtolower($data['key']);abort_if(ProjectConsentDefinition::query()->where('project_id',$projekt->id)->where('key',$key)->exists(),422,'Dieser Schlüssel ist bereits vorhanden.');$definition=ProjectConsentDefinition::query()->create([...$data,'key'=>$key,'project_id'=>$projekt->id,'version'=>1,'created_by_user_id'=>$request->user()->id]);return response()->json(['message'=>'Einwilligung wurde angelegt.','definition'=>$definition],201);}
 public function revise(Request $request,ProjectConsentDefinition $definition){$this->authorizeProject($request,$definition->project);$data=$request->validate($this->rules(false));$new=DB::transaction(function()use($definition,$data,$request){$current=ProjectConsentDefinition::query()->where('project_id',$definition->project_id)->where('key',$definition->key)->lockForUpdate()->orderByDesc('version')->firstOrFail();$current->update(['active'=>false]);return ProjectConsentDefinition::query()->create([...$data,'key'=>$definition->key,'project_id'=>$definition->project_id,'version'=>$current->version+1,'created_by_user_id'=>$request->user()->id]);});return response()->json(['message'=>'Neue Version wurde veröffentlicht.','definition'=>$new]);}
 public function setActive(Request $request,ProjectConsentDefinition $definition){$this->authorizeProject($request,$definition->project);$active=(bool)$request->validate(['active'=>['required','boolean']])['active'];$definition->update(['active'=>$active]);return response()->json(['message'=>'Status wurde aktualisiert.','definition'=>$definition->fresh()]);}
 private function authorizeProject(Request $request,Projekt $project):void{$active=$this->activeProjectContext->currentAvailableFor($request->user());abort_unless($active&&(int)$active->id===(int)$project->id,404);abort_unless($project->portalFeatureEnabled('consents_and_approvals'),404);}
 private function rules(bool $withKey):array{$rules=['title'=>['required','string','max:255'],'purpose'=>['required','string','max:3000'],'content'=>['required','string','max:50000'],'required'=>['required','boolean'],'allow_withdrawal'=>['required','boolean'],'active'=>['required','boolean'],'sort_order'=>['required','integer','min:0','max:9999']];if($withKey)$rules=['key'=>['required','string','max:80','regex:/^[a-z0-9_\-]+$/'],...$rules];return $rules;}
}
