<?php
namespace App\Http\Controllers;
use App\Models\PortalCourse;use App\Models\PortalCourseEnrollment;use App\Models\PortalCourseSession;use App\Models\PortalCourseSessionAttendance;use App\Models\Projekt;use App\Services\Projects\ActiveProjectContext;use Illuminate\Http\Request;use Illuminate\Validation\Rule;
class ProjectCourseSessionController extends Controller
{
 public function __construct(private readonly ActiveProjectContext $activeProjectContext){}
 public function store(Request $request,PortalCourse $course){$this->authorizeProject($request,$course->project);$session=$course->sessions()->create($request->validate($this->rules()));return response()->json(['message'=>'Kurstermin wurde angelegt.','session'=>$session->load('attendance.enrollment.participation.teilnehmer:id,vorname,nachname')],201);}
 public function update(Request $request,PortalCourseSession $session){$this->authorizeProject($request,$session->course->project);$session->update($request->validate($this->rules()));return response()->json(['message'=>'Kurstermin wurde gespeichert.','session'=>$session->fresh()->load('attendance.enrollment.participation.teilnehmer:id,vorname,nachname')]);}
 public function record(Request $request,PortalCourseSession $session){$this->authorizeProject($request,$session->course->project);$data=$request->validate(['attendance'=>['required','array'],'attendance.*.enrollment_id'=>['required','integer'],'attendance.*.status'=>['required',Rule::in(['planned','attended','absent','excused'])],'attendance.*.attended_minutes'=>['nullable','integer','min:0','max:100000'],'attendance.*.note'=>['nullable','string','max:3000']]);$ids=collect($data['attendance'])->pluck('enrollment_id')->unique();$valid=PortalCourseEnrollment::query()->where('course_id',$session->course_id)->whereIn('id',$ids)->count();abort_unless($valid===$ids->count(),422,'Alle Einschreibungen müssen zum Kurs gehören.');foreach($data['attendance'] as $item)PortalCourseSessionAttendance::query()->updateOrCreate(['session_id'=>$session->id,'enrollment_id'=>$item['enrollment_id']],['status'=>$item['status'],'attended_minutes'=>$item['attended_minutes']??null,'note'=>$item['note']??null,'recorded_by_user_id'=>$request->user()->id,'recorded_at'=>now()]);return response()->json(['message'=>'Kursteilnahme wurde gespeichert.','attendance'=>$session->attendance()->with('enrollment.participation.teilnehmer:id,vorname,nachname')->get()]);}
 private function authorizeProject(Request $request,Projekt $project):void{$active=$this->activeProjectContext->currentAvailableFor($request->user());abort_unless($active&&(int)$active->id===(int)$project->id&&$project->portalFeatureEnabled('learning'),404);}
 private function rules():array{return['title'=>['required','string','max:255'],'description'=>['nullable','string','max:5000'],'starts_at'=>['required','date'],'ends_at'=>['required','date','after:starts_at'],'mode'=>['required',Rule::in(['presence','online','hybrid'])],'location'=>['nullable','required_if:mode,presence,hybrid','string','max:255'],'online_url'=>['nullable','required_if:mode,online,hybrid','url','max:2048'],'published'=>['required','boolean']];}
}
