<?php
namespace App\Http\Controllers;
use App\Models\PortalCourse;use App\Models\PortalCourseAssignment;use App\Models\PortalCourseLesson;use App\Models\PortalCourseMaterial;use App\Models\PortalCourseSubmission;use App\Models\Projekt;use App\Services\Projects\ActiveProjectContext;use Illuminate\Http\Request;use Illuminate\Support\Facades\Storage;use Illuminate\Validation\Rule;
class ProjectCourseContentController extends Controller
{
 public function __construct(private readonly ActiveProjectContext $activeProjectContext){}
 public function storeMaterial(Request $request,PortalCourse $course){$this->authorizeProject($request,$course->project);$data=$request->validate(['lesson_id'=>['nullable','integer'],'title'=>['required','string','max:255'],'published'=>['required','boolean'],'sort_order'=>['required','integer','min:0','max:9999'],'file'=>['required','file','max:20480','mimes:pdf,doc,docx,xls,xlsx,ppt,pptx,jpg,jpeg,png,txt,zip']]);$this->lesson($course,$data['lesson_id']??null);$file=$data['file'];$path=$file->store('participant-learning/materials/'.$course->id,'local');$material=PortalCourseMaterial::query()->create(['course_id'=>$course->id,'lesson_id'=>$data['lesson_id']??null,'uploaded_by_user_id'=>$request->user()->id,'title'=>$data['title'],'original_name'=>$file->getClientOriginalName(),'path'=>$path,'mime_type'=>$file->getMimeType()?:'application/octet-stream','size'=>$file->getSize(),'published'=>(bool)$data['published'],'sort_order'=>$data['sort_order']]);return response()->json(['message'=>'Material wurde hochgeladen.','material'=>$material],201);}
 public function updateMaterial(Request $request,PortalCourseMaterial $material){$this->authorizeProject($request,$material->course->project);$data=$request->validate(['title'=>['required','string','max:255'],'published'=>['required','boolean'],'sort_order'=>['required','integer','min:0','max:9999']]);$material->update($data);return response()->json(['message'=>'Material wurde aktualisiert.','material'=>$material->fresh()]);}
 public function downloadMaterial(Request $request,PortalCourseMaterial $material){$this->authorizeProject($request,$material->course->project);abort_unless(Storage::disk('local')->exists($material->path),404);return Storage::disk('local')->download($material->path,$material->original_name,['Content-Type'=>$material->mime_type]);}
 public function storeAssignment(Request $request,PortalCourse $course){$this->authorizeProject($request,$course->project);$data=$request->validate($this->assignmentRules());$this->lesson($course,$data['lesson_id']??null);$assignment=$course->assignments()->create($data);return response()->json(['message'=>'Aufgabe wurde angelegt.','assignment'=>$assignment->load('submissions')],201);}
 public function updateAssignment(Request $request,PortalCourseAssignment $assignment){$this->authorizeProject($request,$assignment->course->project);$data=$request->validate($this->assignmentRules());$this->lesson($assignment->course,$data['lesson_id']??null);$assignment->update($data);return response()->json(['message'=>'Aufgabe wurde aktualisiert.','assignment'=>$assignment->fresh()->load('submissions.enrollment.participation.teilnehmer:id,vorname,nachname')]);}
 public function review(Request $request,PortalCourseSubmission $submission){$submission->load('assignment.course.project');$this->authorizeProject($request,$submission->assignment->course->project);$data=$request->validate(['status'=>['required',Rule::in(['reviewed','revision_requested'])],'score'=>['nullable','numeric','min:0'],'feedback'=>['required','string','max:5000']]);abort_if($data['score']!==null&&$submission->assignment->max_points!==null&&(float)$data['score']>(float)$submission->assignment->max_points,422,'Die Punktzahl überschreitet die Maximalpunktzahl.');$submission->update([...$data,'reviewed_by_user_id'=>$request->user()->id,'reviewed_at'=>now()]);return response()->json(['message'=>'Abgabe wurde bewertet.','submission'=>$submission->fresh()->load('enrollment.participation.teilnehmer:id,vorname,nachname')]);}
 public function downloadSubmission(Request $request,PortalCourseSubmission $submission){$submission->load('assignment.course.project');$this->authorizeProject($request,$submission->assignment->course->project);abort_unless($submission->path&&Storage::disk('local')->exists($submission->path),404);return Storage::disk('local')->download($submission->path,$submission->original_name,['Content-Type'=>$submission->mime_type]);}
 private function authorizeProject(Request $request,Projekt $project):void{$active=$this->activeProjectContext->currentAvailableFor($request->user());abort_unless($active&&(int)$active->id===(int)$project->id&&$project->portalFeatureEnabled('learning'),404);}
 private function lesson(PortalCourse $course,?int $id):void{if($id)abort_unless(PortalCourseLesson::query()->whereKey($id)->where('course_id',$course->id)->exists(),422,'Die Lektion gehört nicht zum Kurs.');}
 private function assignmentRules():array{return['lesson_id'=>['nullable','integer'],'title'=>['required','string','max:255'],'instructions'=>['nullable','string','max:50000'],'due_at'=>['nullable','date'],'max_points'=>['nullable','numeric','min:0','max:999999'],'allow_text'=>['required','boolean'],'allow_file'=>['required','boolean'],'published'=>['required','boolean'],'sort_order'=>['required','integer','min:0','max:9999']];}
}
