<?php
namespace App\Http\Controllers;
use App\Models\PortalCourse;use App\Models\PortalCourseQuiz;use App\Models\PortalCourseLesson;use App\Models\PortalQuizQuestion;use App\Models\Projekt;use App\Services\Projects\ActiveProjectContext;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Validation\Rule;use Illuminate\Validation\ValidationException;
class ProjectCourseQuizController extends Controller
{
 public function __construct(private readonly ActiveProjectContext $activeProjectContext){}
 public function storeQuiz(Request $request,PortalCourse $course){$this->authorizeProject($request,$course->project);$data=$request->validate($this->quizRules());$this->validateLesson($course,$data['lesson_id']??null);$quiz=$course->quizzes()->create($data);return response()->json(['message'=>'Quiz wurde angelegt.','quiz'=>$quiz->load('questions.options')],201);}
 public function updateQuiz(Request $request,PortalCourseQuiz $quiz){$this->authorizeProject($request,$quiz->course->project);$data=$request->validate($this->quizRules());$this->validateLesson($quiz->course,$data['lesson_id']??null);$quiz->update($data);return response()->json(['message'=>'Quiz wurde gespeichert.','quiz'=>$quiz->fresh()->load('questions.options')]);}
 public function storeQuestion(Request $request,PortalCourseQuiz $quiz){$this->authorizeProject($request,$quiz->course->project);$data=$request->validate($this->questionRules());$this->validateOptions($data);$question=DB::transaction(function()use($quiz,$data){$options=$data['options'];unset($data['options']);$question=$quiz->questions()->create($data);foreach($options as $index=>$option)$question->options()->create([...$option,'sort_order'=>$index]);return $question;});return response()->json(['message'=>'Frage wurde angelegt.','question'=>$question->load('options')],201);}
 public function updateQuestion(Request $request,PortalQuizQuestion $question){$question->load('quiz.course.project');$this->authorizeProject($request,$question->quiz->course->project);$data=$request->validate($this->questionRules());$this->validateOptions($data);DB::transaction(function()use($question,$data){$options=$data['options'];unset($data['options']);$question->update($data);$question->options()->delete();foreach($options as $index=>$option)$question->options()->create([...$option,'sort_order'=>$index]);});return response()->json(['message'=>'Frage wurde gespeichert.','question'=>$question->fresh()->load('options')]);}
 private function validateOptions(array $data):void{$correct=collect($data['options'])->where('is_correct',true)->count();if($correct<1||($data['type']==='single'&&$correct!==1))throw ValidationException::withMessages(['options'=>'Mindestens eine, bei Einzelauswahl genau eine Antwort muss richtig sein.']);}
 private function validateLesson(PortalCourse $course,?int $lessonId):void{if($lessonId)abort_unless(PortalCourseLesson::query()->whereKey($lessonId)->where('course_id',$course->id)->exists(),422,'Die Lektion gehört nicht zum Kurs.');}
 private function authorizeProject(Request $request,Projekt $project):void{$active=$this->activeProjectContext->currentAvailableFor($request->user());abort_unless($active&&(int)$active->id===(int)$project->id&&$project->portalFeatureEnabled('learning'),404);}
 private function quizRules():array{return['lesson_id'=>['nullable','integer'],'title'=>['required','string','max:255'],'description'=>['nullable','string','max:5000'],'passing_percent'=>['required','integer','min:0','max:100'],'max_attempts'=>['required','integer','min:1','max:100'],'published'=>['required','boolean'],'sort_order'=>['required','integer','min:0','max:9999']];}
 private function questionRules():array{return['question'=>['required','string','max:5000'],'type'=>['required',Rule::in(['single','multiple'])],'points'=>['required','numeric','min:0.01','max:999999'],'sort_order'=>['required','integer','min:0','max:9999'],'options'=>['required','array','min:2','max:20'],'options.*.label'=>['required','string','max:2000'],'options.*.is_correct'=>['required','boolean']];}
}
